### ISSUE TITLE
Problem with mounting local directory into container

### ISSUE THREAD

**Issue by tomwallis** [rocker-org/rocker-versioned#109]
I'm having trouble mounting a local directory into an RStudio container (applies to all containers from `rocker/rstudio` up). My host system is OSX.

Example:

```sh
docker run -d -p 8787:8787 \
--mount type=bind,source="$(pwd)",destination=/home/rstudio \
-e USER=yourName -e PASSWORD=secretPassword -e ROOT=TRUE \
rocker/rstudio:latest
```

This succeeds in mounting my local directory into rstudio's working directory, and I can see all the files there when I open Rstudio in the browser. However, if I write on the host system or from within the container, no changes are propagated. For example, saving "tmp.R" from Rstudio causes that file to be created with Rstudio's file browser but this does not appear on the host system.

Based on the [documentation here](https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/README.md) I tried including the following line to set user ID in the `docker run` command:

```sh
-e USERID="$(echo $UID)" -e GROUPID="$(echo $GID)" \
```

That succeeds in making my UID in the container the same as on the host (which is not the default), but in that case I don't see any files mapped into Rstudio's working directory, and writing files there causes no change on the host.

This seems to be something to do with running Rstudio – running the container interactively allows me to read and write fine from the command line.

Any pointers on what I'm doing wrong? Same behaviour if I change the `--mount` command to a `-v "$(pwd)":/home/rstudio` command.

**Comment by cboettig** [comment]
Hmm, not sure, that's weird.  I'll try and poke around myself and let you know.

One thing to try: Can you try mounting a subdirectory like `/home/rstudio/Documents` instead of `/home/rstudio`?  While in that can technically work, I try to avoid binding either to the container's or host's $HOME directory directly, since they can have config files etc that are specific to the runtime environment.

**Comment by eddelbuettel** [comment]
Seconded.  Also looks like permissioning to me -- but I never get to use these fancy macOS machinery so I am unsure of the details you may face.

Butb `-v abc:def` has never let me down provided I had access to the to-be shared / mounted dir.

**Comment by tomwallis** [comment]
Thanks for your replies. 

- mounting a subdirectory (`--mount type=bind,source="$(pwd)",destination=/home/rstudio/project`) does not change the behaviour.

- starting the container in interactive mode allows normal read / write:

```
docker run -ti -v "$(pwd)":/home/rstudio/working rocker/rstudio:latest /bin/bash
cd /home/rstudio/working
touch tmp.txt
```

`tmp.txt` appears on the host filesystem. 

So it seems to be a problem that's occurring once RStudio is started.

Another interesting behaviour: if I mount the host directory into `/home/rstudio`, then the subdirectory `kitematic` is created on the host filesystem. Once I'm in RStudio I have the same read / write problem as before.

Could starting RStudio in the container somehow be changing permissions or user behaviour?

**Comment by tomwallis** [comment]
Follow up. Here are the permissions for the mapped bind mount from within the RStudio container (accessing RStudio's Terminal):

```
yourName@1fc3f569f1ab:~/project$ ls -la
total 96
drwxr-xr-x 11 yourName yourName  4096 Nov  7 10:12 .
drwxr-xr-x  5 yourName yourName  4096 Nov  7 10:11 ..
drwxr-xr-x  6 yourName yourName  4096 Nov  7 10:11 code
drwxr-xr-x  2 yourName yourName  4096 Nov  7 10:11 documentation
-rw-r--r--  1 yourName yourName  6148 Nov  7 10:11 .DS_Store
-rw-r--r--  1 yourName yourName   692 Nov  7 10:11 example_docker_start_script
drwxr-xr-x  3 yourName yourName  4096 Nov  7 10:11 figures
drwxr-xr-x  8 yourName yourName  4096 Nov  7 10:11 .git
-rw-r--r--  1 yourName yourName    52 Nov  7 10:11 .gitconfig
-rw-r--r--  1 yourName yourName   522 Nov  7 10:11 .gitignore
-rw-r--r--  1 yourName yourName     0 Nov  7 10:11 .here
drwxr-xr-x  2 yourName yourName  4096 Nov  7 10:11 notebooks
drwxr-xr-x  2 yourName yourName  4096 Nov  7 10:11 publications
drwxr-xr-x  5 yourName yourName  4096 Nov  7 10:11 raw_data
-rw-r--r--  1 yourName yourName   322 Nov  7 10:11 README copy.md
-rw-r--r--  1 yourName yourName   322 Nov  7 10:11 README.md
drwxr-xr-x  4 yourName yourName  4096 Nov  7 10:11 results
-rw-r--r--  1 yourName yourName 20724 Nov  7 10:11 .Rhistory
drwxr-xr-x  4 yourName yourName  4096 Nov  7 10:11 .Rproj.user
```

Here are the permissions on the same directory starting in interactive mode as above:

```
total 52
drwxr-xr-x 18 root    root      576 Nov  7 10:16 .
drwxr-xr-x  1 rstudio rstudio  4096 Nov  7 10:14 ..
drwxr-xr-x  7 root    root      224 Jul 19 07:39 code
drwxr-xr-x 10 root    root      320 May 15 15:00 documentation
-rw-r--r--  1 root    root     6148 Nov  7 10:16 .DS_Store
-rw-r--r--  1 root    root      692 Nov  7 10:11 example_docker_start_script
drwxr-xr-x  4 root    root      128 Apr 23  2018 figures
drwxr-xr-x 16 root    root      512 Nov  7 10:10 .git
-rw-r--r--  1 root    root       52 Nov  6 11:10 .gitconfig
-rw-r--r--  1 root    root      522 May 15 15:46 .gitignore
-rw-r--r--  1 root    root        0 Apr 24  2018 .here
drwxr-xr-x  2 root    root       64 Apr 20  2018 notebooks
drwxr-xr-x  3 root    root       96 Oct  9 12:29 publications
drwxr-xr-x  6 root    root      192 Jun 19 14:09 raw_data
-rw-r--r--  1 root    root      322 Nov  5 13:51 README.md
drwxr-xr-x  4 root    root      128 May  8  2018 results
-rw-r--r--  1 root    root    20724 Nov  5 14:22 .Rhistory
drwxr-xr-x  4 root    root      128 Apr 24  2018 .Rproj.user
```

Does this raise any flags?

**Comment by mkmozgawa** [comment]
I appear to be having the same issues with shared volumes, namely (a) the Kinematic directory appearing inside every folder I create, (b) files created in the browser not showing up on the host. I'm running CentOS 7.5 as the host so it's not just a MacOS issue I'm afraid.

**Comment by cboettig** [comment]
Thanks both for the follow up.  

- re the Kitematic directory; yes the RStudio container creates that to be compatible with file sharing using Docker's Kitematic GUI.  Not sure anyone uses Kitematic these days, but in any event it shouldn't be doing any harm, it's just an empty folder.  If you don't mount the home directory of the container it won't effect the host either.  As mentioned above, we don't recommend mounting the home directory of the container directly to your host -- many applications will add files there (often hidden files).

@tomwallis Can you try without setting the `-e USER=yourName` and see if that fixes things?  

@mkmozgawa We really need more details to understand your problem.  I regularly share files between the container and the host on both MacOS and Linux hosts, so there isn't a general issue here; the problem is likely due to the specifics of your setup or your execution commands

**Comment by eddelbuettel** [comment]
E.g. AppArrmor and other security policies come to mind as well.  As @cboettig says: "it generally works".  I too do a lot of work selectively mounting directories into Docker / Rocker sessions.

**Comment by tomwallis** [comment]
Fixed by @cboettig's suggestion: I removed setting the username in my run command. Evidently, setting a custom username was interfering with rstudio's `root` status, creating permissions issues.

Thanks for your help!

```sh
docker run -d -p 8787:8787 \
--mount type=bind,source="$(pwd)",destination=/home/rstudio/project \
-e PASSWORD=secretPassword -e ROOT=TRUE \
rocker/rstudio:latest
```

**Comment by tomwallis** [comment]
Sorry for the trouble, when it was my run command fault!

**Comment by cboettig** [comment]
no trouble, thanks for the report and glad that resolved it!  I'll have to look into why changing the `USER` name is causing this to fail, but yeah, usually no need to change the default user name.
