### ISSUE TITLE
Add a tidymodels image

### ISSUE THREAD

**Issue by alexhallam** [rocker-org/rocker-versioned#113]
[These images](https://github.com/alexhallam/rocker-tidymodels) were just put together. Would you be willing to put `tidymodels` under the umbrella of rocker? 

The problem that the `tidymodels` image solves is that `rstan` takes a long time to install. This image will decreases the time it takes for users to start using `tidymodels`packages

**Comment by cboettig** [comment]
Thanks. Yes, the rstan issue has come up before, and this is all definitely worth considering.  tidymodels gives a well-defined scope of packages paralleling our existing stack.  

Some details to think out still.  We have an experimental ML stack right now as well, I know for many users these would be quite distinct, but not necessarily -- in particular, see https://greta-stats.org/ which in certain cases may be a very compelling alternative to stan.  

More concretely, some relatively minor issues / comments on the nice images you've shared: for consistency, i would think the `3.5.0` and `3.5.1` tags should install from `install.packages()`, which will lead them to use the version-stable MRAN snapshots as we do in the rest of the versioned stack. There may be a compelling need to have an image with the latest GitHub build, but with the versioned images we try and prioritize consistency and reproducibility. 

Even more minor, your `apt-get update & apt-get install -y` line isn't really doing anything (other than refreshing the apt cache, which just takes up space).  Similarly picky comment, `remotes` is already installed on your base images (on `rocker/tidyverse`) so you can omit that here.  

Anyway, cool stuff and definitely a good discussion to have.  curious for your thoughts on these issues.

**Comment by alexhallam** [comment]
1. I like the idea of the [gpu-rocker-ml](https://hub.docker.com/r/rocker/ml/dockerfile). Having a gpu image would be solving a large pain point. 

2. I am a fan of greta. I think that an ML image which included a tensorflow install could also use greta. I could see a tidymodels  image being distinct or the same as an ML image. If the images were combined then an ML package would contain tidymodels, but also have gpu support, tensorflow, and keras. Now that [R has full Tensorflow API coverage](https://tensorflow.rstudio.com) the image should have everything required to make that connection happen.

3. I will change the GitHub installs to `install.packages()`. I will remove the `apt-get update & apt-get install -y`. Thanks for pointing out that `remotes` is already installed on the base image.

**Comment by eitsupi** [comment]
I close this issue as we can now easily install the tidymodels package on the images like `rocker/tidyverse`, `rocker/ml-verse`.
