### ISSUE TITLE
CMD statement in Dockerfile does not work

### ISSUE THREAD

**Issue by MatthiasHinz** [rocker-org/rocker-versioned#12]
Hi,
I just wondered why R is not starting up when I execute, for instance, the following shell command:

`docker run -i -t rocker/r-ver` 
(a debian shell shows up instead of R)

So I had had a look at the Dockerfiles of the r-ver folder and noticed a bug.

Have a look at
https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/Dockerfile

The last 'RUN'-statement ends with a backslash ` \ ` in line 115. This means that the following CMD command is interpreted as part of the RUN statement and has no effect.

**Comment by cboettig** [comment]
@MatthiasHinz whoops, thanks.  should be fixed soon.
