### ISSUE TITLE
What happened to rocker/hadleyverse

### ISSUE THREAD

**Issue by varemo** [rocker-org/rocker-versioned#125]
Hi,

Sorry if this is the wrong place to post about this. I have a Docker image based on rocker/hadleyverse and tried to rebuild it from the Dockerfile when I realized that rocker/hadleyverse is gone from both GitHub and Dockerhub. I noticed that rocker/hadleyverse is still referenced to here in the README file. How is the plan for the images listed here, e.g. tidyverse? Will they be available to pull for the, say, next 5 years? And does anyone know the reason behind the disappearance of hadleyverse?

**Comment by eddelbuettel** [comment]
Along with "rebranding" upstream. the container was renamed.  No more, no less.

**Comment by Philmod** [comment]
Was it just a "rebranding"? 
It looks like my image that was using hadleyverse is broken with tidyverse.
Could you point me the full diff?

**Comment by eddelbuettel** [comment]
@cboettig switched 'hadleyverse' to 'tidyverse' _years ago_ so I doubt you are looking at a single change but rather a large number across multiple dimensions.  [This commit from 2016 (!!)](https://github.com/rocker-org/rocker-versioned/commit/7936bfdd451505495892a925311d815c601ab2d1) may have been the first.   Our RJournal paper, mostly written in 2017 if memory serves, already alluded to the "former name".
