### ISSUE TITLE
Dplyr 0.7.8 in rocker/shiny-verse:latest

### ISSUE THREAD

**Issue by jpryda** [rocker-org/rocker-versioned#127]
Dplyr 0.8 brings some useful changes over 0.7.8 and I was curious what the best way to update this was.  

It's not quite clear to me how the tidyverse versioning, and its components, are tied and controllable when building containers.  Throwing it in the Dockerfile after `install2.r` didn't do the trick.

**Comment by cboettig** [comment]
Thanks for the report! So looks like I had build caching turned on for Docker Hub, so it was rebuilding only from the Feb 2nd cache, before 0.8 release.  I'll switch that off but it won't rebuild until tomorrow.

By default the container pulls the version from the time it was built, for maximum stability.  Meanwhile, you can always turn that off and get the latest from cran by pointing back to a cran repo, e.g.

```
install2.r -r https://cran.rstudio.com dplyr
```

or  from R

```r
install.packages("dplyr", repos = "https://cran.rstudio.com")
```

Or by setting `repos` option as above in your .Rprofile.

**Comment by jpryda** [comment]
Thanks that makes sense!  Good to know you can pass a repo into `install2.R`
