### ISSUE TITLE
Update VERSIONS.md after 3.5.3

### ISSUE THREAD

**Issue by riccardoporreca** [rocker-org/rocker-versioned#129]
[VERSIONS.md](../blob/master/VERSIONS.md) can be probably updated since 215c4ec4b83b3fc0f621e65bbbd7de55b2b6437e fixed version 3.5.2 and made version 3.5.3 the latest.

**Comment by cboettig** [comment]
Indeed, thanks for the ping!  done now.

**Comment by riccardoporreca** [comment]
@cboettig, I was chasing up some package versioning inconsistency in a setup based on `r-ver/3.5.2`, and realized the `r-ver/3.5.2`image on docker hub actually doesn't refer to the MRAN snapshot of `2019-03-11` (which I assume is the _last date CRAN distributed that R version_) but `2019-03-14`.

``` bash
docker pull rocker/r-ver:3.5.2
docker images rocker/r-ver:3.5.2
docker run --rm rocker/r-ver:3.5.2 R -q -e 'options()$repo'
## 3.5.2: Pulling from rocker/r-ver
## Digest: sha256:6109d3e212e5eacbeccfcf4bfda905c3cdf00d04b08634d89a38ea85a3d6dcf1
## Status: Image is up to date for rocker/r-ver:3.5.2
## REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
## rocker/r-ver        3.5.2               92a3b8472153        10 days ago         605MB
## > options()$repo
##                                             CRAN 
## "https://mran.microsoft.com/snapshot/2019-03-14" 
## > 
## >
```

I guess this might be due to`r-ver/3.5.2` being built on docker hub as _latest_ for another few days after  `2018-03-11`, but not re-built after fixing the date in 215c4ec.

**Comment by cboettig** [comment]
@riccardoporreca yup, that sound right, thanks. I've just tickled `r-ver:3.5.2` to rebuild, let's see if that fixes things now.

**Comment by riccardoporreca** [comment]
Great, thanks for the prompt action @cboettig!
