### ISSUE TITLE
Failed to fetch Debian Jessie images

### ISSUE THREAD

**Issue by mhermans** [rocker-org/rocker-versioned#130]
I am building a basic docker image FROM rocker/verse:latest.

Currently the apt-step fails with

    W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
    E: Some index files failed to download. They have been ignored, or old ones used instead.

This might be related to [Debian Jessie being recently archived on the mirror network](https://unix.stackexchange.com/questions/508724/failed-to-fetch-jessie-backports-repository/508728#508728).

I am however (1) not sure if this is the actual reason for the error, and (2) how to best apply the proposed fix (using `archive.debian.org`) for rocker-images.

**Comment by cboettig** [comment]
Thanks, but can you give us more details necessary to reproduce the behavior you are seeing?  Note that `rocker/verse:latest` is not based on jessie, and should not have jessie repos.  

If you do a fresh pull of `rocker/verse:latest` and run `apt update` in a bash shell, like so:

```
docker run --rm -ti rocker/verse:latest bash
root@43d1633e18ed:/# apt-get update
Ign:1 http://cdn-fastly.deb.debian.org/debian stretch InRelease      
Get:2 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]        
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2,434 B]  
Get:4 http://security-cdn.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [11.1 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7,084 kB]
Get:8 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 Packages [481 kB]
Fetched 7,881 kB in 5s (1,461 kB/s)                                  
Reading package lists... Done
```

Witness all the repos are debian stretch...  You should have to go all the way back to `rocker/verse:3.3.3` to get Debian Jessie (see https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md)...

**Comment by mhermans** [comment]
Thanks for the fast response, a fresh pull fixed it. Was pretty sure it was up to date on this machine, apologies for that.
