### ISSUE TITLE
R-devel has branched to R3.6.0 but no tag for this image yet?

### ISSUE THREAD

**Issue by lshep** [rocker-org/rocker-versioned#132]
Hello, 
It seems that R has branch R-devel into R-3.6.0 alpha.  The R-devel is now recognizing as R3.7  but there is no image/tag yet on dockerhub for R3.6.0  only R3.5.3.  Will the R3.6.0 be up soon?

**Comment by eddelbuettel** [comment]
The R (upstream) release process is well understood and documented (provided you know where to look, eg the r-devel mailing list or the developer.r-project.org site).

R 3.6.0 will come out April 26.  Not before.  As we do every year, we will release and update _once R is released_.  We are currently in the alpha/beta/rc phase and it would be premature to build ont these.  If you care, though, you can get eg Debian binaries for 3.6.0 will I released into Debian's experimental branch (see my email to r-sig-debian).

Thanks for the heads-up; we understand it was well-intentioned.  But we're on top of this :)
