### ISSUE TITLE
Release other r-ver versions

### ISSUE THREAD

**Issue by ColinFay** [rocker-org/rocker-versioned#138]
Hey, 

I see there are no release of specific versions of R 3.x.x — for example the 3.0.0 to 3.0.3, 3.1.1 to 3.1.3, 3.2.1 to 3.2.4... 
Is this on purpose? Do you need help to build them? Will be happy to help. 

Also, any plan on making pre 3.0.0 release available? 
I know it's a little bit tricky as the whole infrastructure relies on MRAN which starts in September 2014, but it would be nice to have access to these old versions.  

Best, 
Colin 

<hr>

_Edit: Here is a list of the versions, with a checkbox to note the completed `r-ver`_

__R (>= 3.0.0)__

+ [ ] R-3.0.0.tar.gz    2013-04-03 09:10	 
+ [ ] R-3.0.1.tar.gz	2013-05-16 09:11	 
+ [ ] R-3.0.2.tar.gz	2013-09-25 09:11	 
+ [ ] R-3.0.3.tar.gz	2014-03-06 09:12	 
+ [x] R-3.1.0.tar.gz	2014-04-10 09:11	 
+ [ ] R-3.1.1.tar.gz	2014-07-10 09:11	 
+ [x] R-3.1.2.tar.gz	2014-10-31 09:11	 
+ [x] R-3.1.3.tar.gz	2015-03-09 09:12	 
+ [x] R-3.2.0.tar.gz	2015-04-16 09:13	 
+ [x] R-3.2.1.tar.gz	2015-06-18 09:13	 
+ [x] R-3.2.2.tar.gz	2015-08-14 09:12	 
+ [x] R-3.2.3.tar.gz	2015-12-10 09:13	 
+ [ ] R-3.2.4-revised.tar.gz2016-2016-03-16 19:46
+ [x] R-3.2.4.tar.gz	2016-03-10 09:13	 
+ [x] R-3.2.5.tar.gz	2016-04-14 18:01	 
+ [x] R-3.3.0.tar.gz	2016-05-03 09:13	 
+ [x] R-3.3.1.tar.gz	2016-06-21 09:21	 
+ [x] R-3.3.2.tar.gz	2016-10-31 09:13	 
+ [x] R-3.3.3.tar.gz	2017-03-06 09:16	 
+ [x] R-3.4.0.tar.gz	2017-04-21 09:14	 
+ [x] R-3.4.1.tar.gz	2017-06-30 09:04	 
+ [x] R-3.4.2.tar.gz	2017-09-28 09:04	 
+ [x] R-3.4.3.tar.gz	2017-11-30 09:05	 
+ [x] R-3.4.4.tar.gz	2018-03-15 09:04	 
+ [x] R-3.5.0.tar.gz	2018-04-23 09:04	 
+ [x] R-3.5.1.tar.gz	2018-07-02 09:04	 
+ [x] R-3.5.2.tar.gz	2018-12-20 09:04	 
+ [x] R-3.5.3.tar.gz	2019-03-11 09:04	 
+ [x] R-3.6.0.tar.gz	2019-04-26 09:05	 

__R (>= 2.0.0)__

+ [ ]	R-2.0.0.tar.gz	2004-10-04 16:16	 
+ [ ]	R-2.0.1.tar.gz	2004-11-15 15:19	 
+ [ ]	R-2.1.0.tar.gz	2005-04-19 09:01	 
+ [ ]	R-2.1.1.tar.gz	2005-06-20 11:28	 
+ [ ]	R-2.2.0.tar.gz	2005-10-06 12:22	 
+ [ ]	R-2.2.1.tar.gz	2005-12-20 11:35	 
+ [ ]	R-2.3.0.tar.gz	2006-04-24 12:37	 
+ [ ]	R-2.3.1.tar.gz	2006-06-01 10:25	 
+ [ ]	R-2.4.0.tar.gz	2006-10-03 12:15	 
+ [ ]	R-2.4.1.tar.gz	2006-12-18 15:06	 
+ [ ]	R-2.5.0.tar.gz	2007-04-24 19:19	 
+ [ ]	R-2.5.1.tar.gz	2007-06-28 13:17	 
+ [ ]	R-2.6.0.tar.gz	2007-10-03 11:02	 
+ [ ]	R-2.6.1.tar.gz	2007-11-26 15:14	 
+ [ ]	R-2.6.2.tar.gz	2008-02-08 12:05	 
+ [ ]	R-2.7.0.tar.gz	2008-04-22 09:45	 
+ [ ]	R-2.7.1.tar.gz	2008-06-23 12:00	 
+ [ ]	R-2.7.2.tar.gz	2008-08-25 09:03	 
+ [ ]	R-2.8.0.tar.gz	2008-10-20 09:31	 
+ [ ]	R-2.8.1.tar.gz	2008-12-22 08:05	 
+ [ ]	R-2.9.0.tar.gz	2009-04-17 10:32	 
+ [ ]	R-2.9.1.tar.gz	2009-06-26 14:04	 
+ [ ]	R-2.9.2.tar.gz	2009-08-24 10:14	 
+ [ ]	R-2.10.0.tar.gz	2009-10-26 09:50	 
+ [ ]	R-2.10.1.tar.gz	2009-12-14 11:15	 
+ [ ]	R-2.11.0.tar.gz	2010-04-22 10:06	 
+ [ ]	R-2.11.1.tar.gz	2010-05-31 10:10	 
+ [ ]	R-2.12.0.tar.gz	2010-10-15 10:33	 
+ [ ]	R-2.12.1.tar.gz	2010-12-16 10:12	 
+ [ ]	R-2.12.2.tar.gz	2011-02-25 12:07	 
+ [ ]	R-2.13.0.tar.gz	2011-04-13 10:31	 
+ [ ]	R-2.13.1.tar.gz	2011-07-08 11:37	 
+ [ ]	R-2.13.2.tar.gz	2011-09-30 09:05	 
+ [ ]	R-2.14.0.tar.gz	2011-10-31 09:09	 
+ [ ]	R-2.14.1.tar.gz	2011-12-22 09:10	 
+ [ ]	R-2.14.2.tar.gz	2012-02-29 09:09	 
+ [ ]	R-2.15.0.tar.gz	2012-03-30 09:09	 
+ [ ]	R-2.15.1-w.tar.gz	2012-06-22 14:17	
+ [ ]	R-2.15.1.tar.gz	2012-06-22 09:09	
+ [ ]	R-2.15.2.tar.gz	2012-10-26 09:10	 
+ [ ]	R-2.15.3.tar.gz	2013-03-01 09:11 	 

__R (>= 1.0.0)__

+ [ ]	R-1.0.0.tgz	2000-02-29 10:03	 
+ [ ]	R-1.0.1.tgz	2000-04-14 11:23	 
+ [ ]	R-1.1.0.tgz	2000-06-15 11:15	 
+ [ ]	R-1.1.1.tgz	2000-08-15 11:16	 
+ [ ]	R-1.2.0.tgz	2000-12-15 11:25	 
+ [ ]	R-1.2.1.tgz	2001-01-15 11:32	 
+ [ ]	R-1.2.2.tgz	2001-02-26 14:18	 
+ [ ]	R-1.2.3.tgz	2001-04-26 14:10	 
+ [ ]	R-1.3.0-recommended.tgz	2001-06-22 14:06	
+ [ ]	R-1.3.0.tgz	2001-06-22 13:03	
+ [ ]	R-1.3.1-recommended.tgz	2001-08-31 15:05	
+ [ ]	R-1.3.1.tgz	2001-08-31 14:58	
+ [ ]	R-1.4.0-recommended.tgz	2001-12-19 11:50	 
+ [ ]	R-1.4.0.tgz	2001-12-19 11:39	
+ [ ]	R-1.4.1-recommended.tgz	2002-01-30 13:13		 
+ [ ]	R-1.4.1.tgz	2002-01-30 13:10	
+ [ ]	R-1.5.0-recommended.tgz	2002-04-29 12:07	
+ [ ]	R-1.5.0.tgz	2002-04-29 12:05	
+ [ ]	R-1.5.1-recommended.tgz	2002-06-17 16:00	
+ [ ]	R-1.5.1.tgz	2002-06-17 13:36		 
+ [ ]	R-1.6.0.tgz	2002-10-01 13:24		 
+ [ ]	R-1.6.1.tgz	2002-11-01 12:22		 
+ [ ]	R-1.6.2.tgz	2003-01-10 16:38		 
+ [ ]	R-1.7.0.tgz	2003-04-16 15:02		 
+ [ ]	R-1.7.1.tgz	2003-06-16 12:34		 
+ [ ]	R-1.8.0.tgz	2003-10-08 13:21		 
+ [ ]	R-1.8.1.tgz	2003-11-21 13:02		 
+ [ ]	R-1.9.0.tgz	2004-04-12 13:30		 
+ [ ]	R-1.9.1.tgz	2004-06-21 13:12	

__R (>= 0.0.0)__

+ [ ]	R-0.49.tgz	1997-04-23 14:53		 
+ [ ]	R-0.50-a1.tgz	1997-07-22 16:44	 
+ [ ]	R-0.50-a4.tgz	1997-09-10 14:31	 
+ [ ]	R-0.60.0.tgz	1997-12-04 09:58	 
+ [ ]	R-0.60.1.tgz	1997-12-07 02:59	 
+ [ ]	R-0.61.0.tgz	1997-12-22 00:00	 
+ [ ]	R-0.61.1.tgz	1998-01-13 00:00	 
+ [ ]	R-0.61.2.tgz	1998-03-18 00:00	 
+ [ ]	R-0.61.3.tgz	1998-05-03 00:00	 
+ [ ]	R-0.62.0.tgz	1998-06-15 00:00	 
+ [ ]	R-0.62.1.tgz	1998-06-15 00:00	 
+ [ ]	R-0.62.2.tgz	1998-07-10 11:59	 
+ [ ]	R-0.62.3.tgz	1998-08-28 11:01	 
+ [ ]	R-0.62.4.tgz	1998-10-24 00:00	 
+ [ ]	R-0.63.0.tgz	1998-11-14 04:57	 
+ [ ]	R-0.63.1.tgz	1998-12-05 02:25	 
+ [ ]	R-0.63.2.tgz	1999-01-12 02:21	 
+ [ ]	R-0.63.3.tgz	1999-03-06 04:27	 
+ [ ]	R-0.64.0.tgz	1999-04-08 01:48	 
+ [ ]	R-0.64.1.tgz	1999-05-08 02:55	 
+ [ ]	R-0.64.2.tgz	1999-07-05 21:15	 
+ [ ]	R-0.65.0.tgz	1999-08-28 00:18	 
+ [ ]	R-0.65.1.tgz	1999-10-07 01:46	 
+ [ ]	R-0.90.0.tgz	1999-11-22 18:07	 
+ [ ]	R-0.90.1.tgz	1999-12-15 14:05	 
+ [ ]	R-0.99.0.tgz	2000-02-07 13:09	 
+ [ ]	R-0.99.0a.tgz	2000-02-09 12:28	 

> From https://cran.r-project.org/src/base/

__Debian versions__

![debian-tl](https://user-images.githubusercontent.com/17936236/57410493-37447f80-71eb-11e9-91d8-8a7147e08f00.png)

> from https://en.wikipedia.org/wiki/Template:Timeline_Debian_GNU/Linux

**Comment by cboettig** [comment]
@ColinFay Thanks for bringing this up.  Yup, it would be nice to have more older images, and the short answer is just that we haven't had time to implement these carefully yet.  so any PRs to that effect would be most welcome!

The farther you go back obviously the harder it is to supply consistent image suite, but it would definitely be doable, at least for the base `r-ver` image.  

As you've probably seen in [VERSIONS](https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md), I've tried to stick with a contemporary debian release, which is a convenient way to provide at least a roughly close approximation of the system libraries and compilers under use at that time.  Getting R to build on the older releases requires a bit of tweaking of the basic recipe, though I believe our 3.1.0 recipe builds on wheezy successfully so that could probably cover all the 3.x.x range at least.  (Though it's not clear if the base `wheezy` docker image is still maintained).  

MRAN is another issue.  Again this one isn't a show-stopper as packages could be installed from CRAN archive versions instead, but requires more effort; and of course many packages in `tidyverse` didn't exist back then (and several of them are not compatible with R versions older than 3.1 or so).  But it would still be good to have `r-ver` and maybe `rstudio` images even without extending the rest of the stack back that far.  

Thanks again, and any thoughts on how such images should be built or contributions on this would be most welcome!

**Comment by eddelbuettel** [comment]
With some care it should be possible to reconstruct things.  Debian has a [snapshot archive](http://snapshot.debian.org/) you could use for "host OS" at a point in time, and I presume one could roll back history to the snapshot of files at a point in time.

**Comment by ColinFay** [comment]
Thanks for your answers! 

I think I'll start with the most recent missing one (R 3.2.4 I think) and go backward in time — I think the more we go in the past the more complicated it can get, so beginning with a recent version seems like the best place to start.

Colin

**Comment by dheiman** [comment]
You may want to note that archived Debian release (e.g. Jessie) will need their Dockerfiles modified in order to successfully run any `apt-get` commands.

For Jessie, adding the following before running any `apt-get` commands will fix the issue (based on several stack-overflow entries).

```Dockerfile
RUN echo "deb [check-valid-until=no] http://cdn-fastly.deb.debian.org/debian jessie main" > /etc/apt/sources.list.d/jessie.list
RUN echo "deb [check-valid-until=no] http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list
RUN sed -i '/deb http:\/\/deb.debian.org\/debian jessie-updates main/d' /etc/apt/sources.list
RUN apt-get -o Acquire::Check-Valid-Until=false update
RUN echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf
```

**Comment by cboettig** [comment]
@dheiman Thanks!  Would you be interested in sending a PR against the `jessie` based images?

(For caching purposes, it might be nice to combine these in a single RUN command).

**Comment by ColinFay** [comment]
AFAICT it seems to be still supported in `jessie`: 

```
$ docker run rocker/r-ver:3.3.3 apt-get update
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:2 http://deb.debian.org jessie Release.gpg [1,652 B]
Get:3 http://deb.debian.org jessie Release [77.3 kB]
Get:4 http://deb.debian.org jessie/main amd64 Packages [9,098 kB]
Get:5 http://security.debian.org jessie/updates/main amd64 Packages [871 kB]
Fetched 10.1 MB in 8s (1,127 kB/s)
Reading package lists...
```

But not on `wheezy` based image: 

```
$ docker run rocker/r-ver:3.1.3 apt-get update
Get:1 http://archive.debian.org wheezy Release.gpg [2,373 B]
Get:2 http://archive.debian.org wheezy/updates Release.gpg [1,601 B]
Get:3 http://archive.debian.org wheezy Release [191 kB]
Get:4 http://archive.debian.org wheezy/updates Release [52.3 kB]
E: Release file for http://archive.debian.org/debian-security/dists/wheezy/updates/Release is expired (invalid since 111d 18h 46min 0s). Updates for this repository will not be applied.
```

It seems like `Jessie` will be supported until 2020-06 so it should be fine till then: <https://wiki.debian.org/DebianReleases>

So the update for `apt-get` needs to be done with `wheezy` based images.

**Comment by ColinFay** [comment]
Other question: 

Current 3.1.0 <https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/3.1.0/Dockerfile> has a build-date "2014-09-17", but this version has been released on the 2014-04-10. 

I suspect this is for MRAN compatibility reasons. Is the plan to use this minimal MRAN date for all the pre 2014-09-17 images ? (I'm asking before I start building these images :) )

**Comment by cboettig** [comment]
@ColinFay re the MRAN date, yeah, that's the first date for which there is an MRAN record, but I don't think it's great to use that for earlier images.  I'm not sure what is the best choice here, but my instinct is that we should simply not fix any default CRAN repo/mirror in these images.  

If users want to add contemporary versions of packages to these images, they are on there own, as it probably will never make sense to propagate these up through the stack (i.e. tidyverse etc add a lot of packages that didn't even exist back then).  Some may want to use the older images explicitly with newer versions of packages just to check backwards compatibility anyway.  By leaving the mirror unset, at least that makes it a bit more explicit that `install.packages()` in the pre 3.2 images doesn't get an MRAN.  


Of course we should clearly document whatever we do as well.

**Comment by nuest** [comment]
@barryrowlingson mentioned on Twitter that he compiled R `0.49`. Maybe he'd like to share his process here?

https://twitter.com/geospacedman/status/1166302010511110145?s=09)

**Comment by barryrowlingson** [comment]
I've a repo here: https://gitlab.com/b-rowlingson/r-0.49 that I've just checked in a working version.  Four changes gets me something that compiled except currently the `mva` and `eda` packages don't compile.

There's also plenty of compiler warnings and notes - but they may well have happened back in 1997 too!

**Comment by barryrowlingson** [comment]
Yeah there's no point trying to get something this old, busted, and useless into the Rocker Project - but if I find a 1997 slackware on docker hub I'll let you know :)

**Comment by cboettig** [comment]
Thanks @ColinFay  for your work on these!
