### ISSUE TITLE
install_tensorflow() works in R but not RStudio

### ISSUE THREAD

**Issue by alinaselega** [rocker-org/rocker-versioned#154]
I encountered a problem with installing Tensorflow on top of the rocker/tidyverse image.

Here is a sample Dockerfile I used. It installs Python dependencies and the tensorflow R package:

```
FROM rocker/tidyverse
RUN apt-get update && apt-get install -y python-pip
RUN pip install virtualenv
RUN Rscript -e 'install.packages("tensorflow"); tensorflow::install_tensorflow(extra_packages ="tensorflow-probability")'
```

Upon building the image (`tf-test`) and running the local RStudio server with the following command, I find that the Tensorflow installation is missing.

`docker run --rm -e PASSWORD=test -p 127.0.0.1:8787:8787 --name tf tf-test`

![screenshot1](https://user-images.githubusercontent.com/10548038/59679305-5bba5100-91c6-11e9-8248-01c00d8db85d.png)

However, if I open a shell inside the container and run R in the console, the installation exists:

```
docker exec -it tf bash
R
> library(tensorflow)
> sess = tf$Session()
2019-06-18 11:27:29.725750: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-06-18 11:27:29.729222: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1947175000 Hz
2019-06-18 11:27:29.729525: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x55584b18c5d0 executing computations on platform Host. Devices:
2019-06-18 11:27:29.729570: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
> hello <- tf$constant('Hello, TensorFlow!')
> sess$run(hello)
[1] "Hello, TensorFlow!"
```

I noticed the Python location that RStudio uses to be different from the location used by R run in the console. Running this in RStudio returns:

```
> Sys.which("python")            
                 python  
"/usr/bin/python"
```

Whereas after creating a Tensorflow session in R run in console, the Python location changes to:

```
> sess = tf$Session()
> Sys.which("python")
                                      python
"/root/.virtualenvs/r-tensorflow/bin/python"
```

A solution I found is to install Tensorflow and tensorflow-probability manually rather than with the `install_tensorflow()` function in R, modifying the Dockerfile to be:

```
FROM rocker/tidyverse
RUN apt-get update && apt-get install -y python-pip
RUN pip install virtualenv
RUN pip install tensorflow tensorflow-probability
RUN Rscript -e 'install.packages("tensorflow")'
```

With this image, Tensorflow installation exists in RStudio. However, all recommendations for installing Tensorflow in R say to use the `install_tensorflow()` function and I don't know if it does something else I might be missing with the pip installation.

Do you have any advice on what the right way to do this is?

**Comment by cboettig** [comment]
@alinaselega Yes, this is a bit tricky, so you might want to try our `rocker/ml` images (or `rocker/ml-gpu` if you have an NVidia GPU handy) instead, see https://github.com/rocker-org/ml.  These are still a work in progress, so feedback welcome.


`install_tensorflow()` is just a helper function to do the exact same thing you did more manually.  Note that `install_tensorflow()` is configurable, the default is to use `virtualenv` and to create said `virtualenv` in the user's home dir -- since the Docker build phase runs as root this is in the `root` user's home dir, as you saw above.  When you ran in 'shell' mode, you ran is the `root` user, so R could find `tensorflow`.  `install_tensorflow()` also currently has the side-effect of deleting the existing virtualenv you install it into, which is why it defaults to creating a new virtualenv location (`r-tensorflow`) rather than using the default provided by `reticulate` package.

You'll see in our configuration we make a system-level `virtualenv` inside `/opt/` that both users and root can write to and use, and set that using `RETICULATE_PYTHON_ENV` as the default virtualenv, so that users don't have to declare that when they start up R.  

HTH!  feedback welcome.

**Comment by alinaselega** [comment]
@cboettig Thank you for your advice! As I am the only user running the RStudio instance locally, I suppose I could use the `-e ROOT=TRUE` flag as you discussed in [this issue](https://github.com/rocker-org/rocker/issues/94) to fix the original problem?

However, using `rocker/ml` images seems like a better supported option so I will use that instead.

**Comment by cboettig** [comment]
`-e ROOT=TRUE` will just give your R user `sudo` privileges, so it won't fix your issue.  

You could have done something like:

```
FROM rocker/tidyverse
RUN apt-get update && apt-get install -y python-pip
RUN pip install virtualenv
USER rstudio
RUN Rscript -e 'install.packages("tensorflow"); tensorflow::install_tensorflow(extra_packages ="tensorflow-probability")'
USER root
```

to switch to the `rstudio` user when installing `tensorflow`, but I think `rocker/ml` setup is a cleaner way to do this, and installs some additional nice ML stuff (xgboost, h20) you might use.  If you just want `tensorflow` without that additional stuff, there's `rocker/tensorflow` and `rocker/tensorflow-gpu`.

**Comment by alinaselega** [comment]
That makes sense, thanks!

**Comment by achamess** [comment]
I'm having a similar issue. Trying to make a Docker with Tensorflow installed so I can run another package that depends on it. 

I'm building my docker image from the base `ml-gpu`

But this is what is happening

```
Removing intermediate container 50370500da5a
 ---> 4c94e64b3b0e
Step 8/14 : RUN echo "alias python='python3.6.8'" >> ~/.bashrc
 ---> Running in 8ae126f245d7
Removing intermediate container 8ae126f245d7
 ---> 9a295f7419e7
Step 9/14 : RUN echo "$(which python)"
 ---> Running in 8b00932722f1
/opt/virtualenvs/r-tensorflow/bin/python
Removing intermediate container 8b00932722f1
 ---> d30f8afe0401
Step 10/14 : RUN pip3 install virtualenv
 ---> Running in b1a8f3c1e279
Requirement already satisfied: virtualenv in /opt/virtualenvs/r-tensorflow/lib/python3.5/site-packages
Removing intermediate container b1a8f3c1e279
 ---> b950ec6b7764
Step 11/14 : RUN echo "$(which virtualenv)"
 ---> Running in 823d2c6f46d7
/opt/virtualenvs/r-tensorflow/bin/virtualenv
Removing intermediate container 823d2c6f46d7
 ---> cb6203557b88
Step 12/14 : RUN echo "$(python --version)"
 ---> Running in 98fc25570518
Python 3.5.3
Removing intermediate container 98fc25570518
 ---> ce26db0e08a0
Step 13/14 : RUN Rscript -e "library(tensorflow);install_tensorflow(version = '1.15.0rc2-gpu')"
 ---> Running in 9920cd6e11f7
Creating virtualenv for TensorFlow at  /opt/virtualenvs/r-tensorflow 
sh: 1: /usr/local/bin/virtualenv: not found
Error: Error 127 occurred creating virtualenv at /opt/virtualenvs/r-tensorflow
In addition: Warning message:
In system2(virtualenv, shQuote(c("--system-site-packages", "--python",  :
  error in running command
Execution halted
```

It looks like it's looking for the `virtualenv` module in `/usr/local/bin/virtualenv` but it's been loaded instead at `/opt/virtualenvs/r-tensorflow/bin/virtualenv`. Any thoughts? I'm tempted to just not do this in Docker and set up on my local machine, but it would be nice to have a docker solution.

**Comment by cboettig** [comment]
@achamess  thanks for the bug report, I'll take a look.  Meanwhile, can you try using `rocker/ml:cuda-10.0` instead?

**Comment by achamess** [comment]
@cboettig That seems to have done the trick. Thanks!
