### ISSUE TITLE
Can not install Seurat with install.packages("Seurat")

### ISSUE THREAD

**Issue by JingqunMa** [rocker-org/rocker-versioned#155]
ERROR: dependency 'png' is not available for package 'Seurat'
* removing '/usr/local/lib/R/site-library/Seurat'
Warning in install.packages :
  installation of package 'Seurat' had non-zero exit status

**Comment by eddelbuettel** [comment]
You need to install `png` first, which may require a `libpng-dev` package.  Please show the errors you get when you try to install `png` -- in short, no `Seurat` without `png` as per [the package page too](https://cloud.r-project.org/web/packages/Seurat/index.html)

**Comment by JingqunMa** [comment]
Thank you @eddelbuettel for the reply. Here is the error when I tried to install png> install.packages("png")
Installing package into â/usr/local/lib/R/site-libraryâ
(as âlibâ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2019-06-16/src/contrib/png_0.1-7.tar.gz'
Content type 'application/octet-stream' length 24990 bytes (24 KB)
==================================================
downloaded 24 KB

* installing *source* package âpngâ ...
** package âpngâ successfully unpacked and MD5 sums checked
** using staged installation
** libs
gcc -I"/usr/local/lib/R/include" -DNDEBUG   -I/usr/local/include  `libpng-config --cflags` -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c read.c -o read.o
/bin/bash: libpng-config: command not found
read.c:3:17: fatal error: png.h: No such file or directory
 #include <png.h>
                 ^
compilation terminated.
/usr/local/lib/R/etc/Makeconf:167: recipe for target 'read.o' failed
make: *** [read.o] Error 1
ERROR: compilation failed for package âpngâ
* removing â/usr/local/lib/R/site-library/pngâ

The downloaded source packages are in
	â/tmp/Rtmp7kmOsC/downloaded_packagesâ
Warning message:
In install.packages("png") :
  installation of package âpngâ had non-zero exit status

**Comment by JingqunMa** [comment]
libpng-dev also doesn't can't be installed. Here is the error:
install.packages("libpng-dev")
Installing package into â/usr/local/lib/R/site-libraryâ
(as âlibâ is unspecified)
Warning message:
package âlibpng-devâ is not available (for R version 3.6.0)

**Comment by eddelbuettel** [comment]
> read.c:3:17: fatal error: png.h: No such file or directory #include <png.h>

You deal with that at the _shell command prompt_ not the R prompt as it is a system library.

**Comment by eddelbuettel** [comment]
```sh
edd@rob:~$ dpkg -S /usr/include/png.h
libpng-dev:amd64: /usr/include/png.h
edd@rob:~$ 
```

So  you need `sudo apt-get install libpng-dev` to move along.

**Comment by JingqunMa** [comment]
I am running the docker on a cloud machine which I don't have sudo access.

**Comment by g-torr** [comment]
a workaround for not using sudo  is  change the PATH and remove temporary the paths  pointing  to anaconda  for the installation, see  https://stackoverflow.com/a/59556852
In practise, type in your terminal 
echo $PATH
 copy the output on a text editor and  remove  lines like: /opt/apps/devtools/anaconda/2019.3/python/3.7.3/bin
export PATH = 'paste the new path here '

**Comment by eddelbuettel** [comment]
I suggest we delete this comment.  Mixing Rocker with anaconda is a not generally a good idea.
