### ISSUE TITLE
curl command not found in container

### ISSUE THREAD

**Issue by nickforr** [rocker-org/rocker-versioned#157]
I'm using bash in the rocker/verse container (having run `docker exec -ti <container-id> bash`) and trying to download something using curl but I'm seeing `bash: curl: command not found`

I know I can install this with apt-get etc but I'm wondering why it's not available given that the dockerfiles themselves use curl commands?

Thanks

**Comment by eddelbuettel** [comment]
There are many commands available for Linux, and we cannot ship all of them.  On the margin each of these requests is "useful" and "has a point" -- but we need to draw a line somewhere.  

Maybe you can "fix" your download problem using the `curl` package from R?  

In short, I understand your issue but still think we may want to refrain from installing.  But it is not clear cut as the curl (command-line) package is indeed small-ish - 400kb on my Ubuntu 19.04 desktop.

**Comment by nickforr** [comment]
Thanks, I can work around this ok. I think it’s just I haven’t fully understood the relationship between commands in the Dockerfile (where curl is used) and what’s then available in the container when it’s running.

(Happy for you to close this and thanks for all your efforts with rocker, it’s very useful).

**Comment by eddelbuettel** [comment]
Can you link to the Dockerfile in question?  If and when a command is used, it should indeed be in the container (_e.g._ `install.r`).  Could you by chance be confusing different `Dockerfile`s and containers?

**Comment by nickforr** [comment]
It's in the r-ver dockerfile; line 72 looks to install curl and line 75 looks to use it:
[](https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/Dockerfile)

**Comment by eddelbuettel** [comment]
Indeed.  But listed under `BUILDDEPS` so maybe a temporary use.

**Comment by nickforr** [comment]
Ah, I missed line 126: `apt-get remove --purge -y $BUILDDEPS`
Thanks.
