### ISSUE TITLE
Installing additional linux packages (curl)

### ISSUE THREAD

**Issue by alexhallam** [rocker-org/rocker-versioned#159]
I need to build an image which includes some Microsoft ODBC utilities.
I have successfully installed these utilities on a few other linux machines 
using the docs [here](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-2017).

The problem I am running into is that I need `curl` to install these utilities and when I 
try to use or install curl I get errors.

-------------------------------------------------------------------------------------------------------

> /bin/sh: 1: curl: not found

This can be reproduced with the following Dockerfile and running `docker build -t this/image .`

```
FROM rocker/r-ver:3.6.0
RUN curl google.com
```

Since curl was not found I attempted to install it with the following Dockerfile

```
FROM rocker/r-ver:3.6.0
RUN apt-get update -qq && apt-get -y --no-install-recommends install curl
```
when attempting to build this image I got the error:

```
W: Failed to fetch http://deb.debian.org/debian/dists/stretch/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/stretch/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/stretch-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package curl
``` 

### Additional Web Searching

1. 

A related issue due to network settings, but I am using a Linux as the host:
https://stackoverflow.com/questions/55285781/docker-build-rocker-r-ver3-4-4-fail

2. 

Maybe installing a `verse` image instead of a `ver` image, but I do not need all of the Rstudio peices. 
I am guessing this would have curl installed and useable with `RUN curl google.com`
https://stackoverflow.com/questions/41895615/docker-how-to-install-rcurl-to-docker-container

3. 

The rocker docs have the following note.

> Note: If you get an error such as "E: The value 'testing' is invalid for APT::Default-Release as such a release is not
> available in the sources", you should run apt-get update. In general with docker images you are expected to run apt-get
> update before installing.

I don't think this applies, but if it did I do already have `apt-get update` 

https://github.com/rocker-org/rocker/wiki/Using-the-RStudio-image

**Comment by cboettig** [comment]
Thanks for the report.  Like the error says, this is probably just a `Temporary failure resolving 'deb.debian.org'`.  The internet does that some times.  You can check in your browser if the urls resolve.  Please try again now or in a few minutes and things should be fine.  

Re verse, correct, `curl` is in `verse` and generally we recommend these "batteries included" images for any users who want to save time or effort in constructing custom installs.  Correct, it does build on rstudio which makes it maybe 10% larger (and no doubt tons of other stuff that you don't need either!) but these extra bytes are probably not really in your way.

**Comment by alexhallam** [comment]
Thanks for the answer. It does seem that everything is working now. All it took was waiting a till later in the day to build the image. I was not aware that `resolving 'deb.debian.org'` was a thing. I will give the `verse` images a try.
