### ISSUE TITLE
enable optional check `checkbashisms`

### ISSUE THREAD

**Issue by rnuske** [rocker-org/rocker-versioned#166]
The svn revision 77306 of R (mirrored in r-source changset [0866fd0](https://github.com/wch/r-source/commit/0866fd0d4a2cefb3547717d13a08cf63a7e996bb)) introduced an new check for 'bashism' in `configure` and `cleanup` files. It produces a warning if the script `checkbashisms` cannot be found. This script is part of the debian package `devscripts`.

Could the debian package  `devscripts` be added to `r-ver/devel`?

**Comment by cboettig** [comment]
Thanks @rnuske , would you like to make a PR for this against the [r-ver/devel Dockerfile](https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/devel/Dockerfile)?  

(Also raised by @dbaston in https://github.com/rocker-org/rocker/issues/365)

**Comment by rnuske** [comment]
Yes, thanks for the possibility to contribute.
