### ISSUE TITLE
Version-stable TeXLive for TinyTeX?

### ISSUE THREAD

**Issue by riccardoporreca** [rocker-org/rocker-versioned#169]
The `rocker/verse` images rely on [TinyTeX](https://yihui.name/tinytex/) as a LaTeX installation, which is meant to always install and refer to the latest version of TeXLive and LaTeX packages (see [FAQ](https://yihui.name/tinytex/faq/)).

This might not be ideal for usage in Docker images, especially in the context of a version-stable stack. Examples of drawbacks / issues are as follows. 

1. Once the a new TeXLive yearly release is available (e.g. 2018 -> 2019), a [re-install of TinyTeX](https://yihui.name/tinytex/#maintenance) is needed to e.g. install new packages in (running) containers based on images built with the older release of TeXLive, for instance as part of a customized PDF R Markdown output. A way to see this in action is `docker run --rm rocker/verse:3.5.2 R -e 'tinytex::tlmgr_install("fancyhdr")'` => ` Remote repository is newer than local (2018 < 2019)`.

2. Each time a `rocker/verse` image is re-built, new versions of TeXLive as well as LaTeX packages kick in with the new TinyTeX install. This is possibly not desired also given Rocker's [Maintenance and Updates](https://github.com/rocker-org/rocker-versioned#maintenance-and-updates) approach: "This allows the images to receive security updates to any packages installed from the debian repositories, but will not in general change the versions of any software and is very unlikely to break anything".

Point 2. is especially relevant for re-builds of images for previous R versions, i.e. up to 3.6.0 as of 2019-11-03. With a re-build, new versions of LaTeX packages would be included with possible bugs kicking in. This is indeed the case currenty, since a recent version of the `graphicx` LaTeX package introduced a bug (see jgm/pandoc#5848, miraisolutions/SmaRP#152), preventing images from being included with the `xelatex` engine. If `rocker/verse:3.6.0` was rebuilt today, this would (silently) introduce issues when rebuilding Docker images based on it and using `xelatex`+images.

These problems could be solved by fixing the version of TeXLive and LaTeX packages using the new [tlnet archive](https://www.texlive.info/tlnet-archive), made [available recently](https://www.preining.info/blog/2019/09/tex-services-at-texlive-info/) and providing TeXLive snaphots of CTAN (similar to the MRAN), see also https://www.tug.org/texlive/pkginstall.html. TinyTex in fact supports specifying a custom CTAN repo via the environment variable `CTAN_REPO` ([tools/install-base.sh#L5](https://github.com/yihui/tinytex/blob/9efbce0c77179eac2f6800f08b768aefa1917085/tools/install-base.sh#L5)), which could be used to make the TinyTeX install version-stable.

This is approach is currently being used in the [miraisolutions/SmaRP](https://github.com/miraisolutions/SmaRP) project: [docker/install_tinytex.sh](https://github.com/miraisolutions/SmaRP/blob/85c297f77f24d1b19fc77066b12f5fd849fe935c/docker/install_tinytex.sh#L10-L12), [Dockerfile](https://github.com/miraisolutions/SmaRP/blob/85c297f77f24d1b19fc77066b12f5fd849fe935c/Dockerfile#L30-L35).

If this is deemed relevant to include in `rocker/verse`, one may not even use daily snapshots but stick to the snapshot of the latest frozen TeXLive release as "stable" release, in order to minimize uncontrolled updates with daily builds also for the current version of R.

**Comment by cboettig** [comment]
@riccardoporreca Thanks a lot for this, I think this is an important issue and appreciate you highlighting it here.  Just to make sure I follow, you'd suggest just using a custom `CTAN_REPO` as in your example, while still using the TinyTeX (and thus rmarkdown users could still get on-the-fly installs of `*.sty` files)?  This sounds quite compelling to me!  Want to send a PR for this (updating both `verse/Dockerfile` and `verse/devel/Dockerfile` at least .. though given the stability issue we should maybe backport it through all the `verse` instances that are tinytex based, I think that's back as far as all the `3.4.3` tag...)

@yihui, I would love to get your take here as well.

**Comment by riccardoporreca** [comment]
@cboettig Indeed, despite the lengthy context, the main suggestion is to indeed still rely on the excellent TinyTeX (with all the on-the-fly benefits) but use a custom, version-stable `CTAN_REPO` from the [tlnet archive](https://www.texlive.info/tlnet-archive).

After some more thoughts, one option to pick the TeXLive snapshot is to bind it to the version of TeXLive normally shipped as `texlive-*` packages in the Debian image each `rocker/r-ver` is created `FROM`. This would basically mean using the TinyTeX install in the `rocker/verse` as a tiny, container-friendly replacement for the TeXLive install one would get via `apt-get` for the specific Debian release.

The information can be found at https://www.tug.org/texlive/debian.html. The [tlnet archive](https://www.texlive.info/tlnet-archive) goes back to 2009 with yearly frozen TeXLive releases, which is enough to cover the oldest Debian release in Rocker (wheezy).

If we can agree on this (or an alternative) as a sensible approach, I will be happy to send a PR including backports to each older tag including TinyTeX.

**Comment by yihui** [comment]
I have never heard of texlive.info before (thanks @riccardoporreca), but this sounds like a good idea to me.

**Comment by cboettig** [comment]
Thanks @yihui!  @riccardoporreca want to send us a PR for this then?

**Comment by riccardoporreca** [comment]
@yihui, texlive.info was a nice revelation for me too!

@cboettig, I will be happy to contribute with a PR and will be using to use the TeXLive 2016 snapshot from the tlnet archive (http://www.texlive.info/tlnet-archive/2017/04/13/tlnet), to be inline with the Debian stretch base images (all tags of `rocker/verse` using TinyTeX are based on stretch). We have already successfully used the same approach in [SmaRP](https://github.com/miraisolutions/SmaRP/issues/152#issuecomment-549738666), also working around an issue with https, since back in TeXLive 2016 [install-tl](https://www.texlive.info/tlnet-archive/2017/04/13/tlnet/install-tl) only supported http and ftp for the `-repository` command-line argument.

**Comment by cboettig** [comment]
@riccardoporreca sounds good.  Note that `rocker/verse:devel` is now on `debian:buster` (at least it should be!) and we'll move `latest` to buster as well at the next R release.

**Comment by riccardoporreca** [comment]
@cboettig, see PR #171, which also include details about workarounds for TeXLive 2016.

**Comment by norbusan** [comment]
> I have never heard of texlive.info before (thanks @riccardoporreca), but this sounds like a good idea to me.

Texlive.info is my server ;-)

**Comment by yihui** [comment]
@norbusan Awesome! Thanks!
