### ISSUE TITLE
verse images fail to build due to 404

### ISSUE THREAD

**Issue by zeehio** [rocker-org/rocker-versioned#174]
The link at https://github.com/rocker-org/rocker-versioned/blob/0842c3b58e6e5ed8aac2f8e15705f68f3c6fc50b/verse/Dockerfile#L13 is returning 404.

I have already reported this at https://github.com/yihui/travis-bin/issues/2 so the link is fixed, but for now the verse docker images fail to build

**Comment by yihui** [comment]
Fixed now. Thank you!

**Comment by cboettig** [comment]
thanks both!
