### ISSUE TITLE
Please upgrade `git` version

### ISSUE THREAD

**Issue by psychelzh** [rocker-org/rocker-versioned#181]
Current `git` version is `2.11.0`, which is not supported in [the v2 of actions/checkout](https://github.com/actions/checkout/releases/tag/v2-beta). Specifically, when I use current version of `rocker/verse` in github actions using the latest version of `checkout`, it reports the following error:

>##[error]Minimum required git version is 2.18. Your git ('/usr/bin/git') is 2.11.0

**Comment by eddelbuettel** [comment]
Could this be because you opted for _versioned_ Rocker image which is by design frozen in time?

```sh
edd@rob:~$ git --version
git version 2.20.1
edd@rob:~$ 
```

**Comment by psychelzh** [comment]
I am sorry that I don't know what should be done, but I used this container: `rocker/verse:latest`.

**Comment by cboettig** [comment]
@psychelzh yeah, `rocker/verse:latest` is still based on `debian:stretch`, which was the latest stable release of Debian at the time R 3.6.1 was released, see:  https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md

Good news is that with 3.6.2 release coming up, we'll move to the current stable, which is now buster (https://packages.debian.org/buster/git).  

`rocker/verse:devel` is already on buster.
