### ISSUE TITLE
Difficulties to install datasets.load package in rstudio

### ISSUE THREAD

**Issue by samos999** [rocker-org/rocker-versioned#183]
Hi I'm trying to install datasets.load package but it seems impossible. 
I haven't any errors showing up but after few minutes rstudio appear to be jam. 
this is the print screen I have : 

<img width="1270" alt="Capture d’écran 2019-12-11 à 10 40 28" src="https://user-images.githubusercontent.com/47973297/70610539-09516e80-1c04-11ea-8372-c84889eae0b8.png">

and here we have the CPU given by top command 

<img width="608" alt="Capture d’écran 2019-12-11 à 10 36 49" src="https://user-images.githubusercontent.com/47973297/70610990-c93ebb80-1c04-11ea-9070-4d6da1dd7ddf.png">

I'm running rstudio on AWS. 
Regards

**Comment by samos999** [comment]
Actually I think in datasets.load one package ( httpuv ) may be the main issue. 
I have the same difficulty when I try to get only the package:  httpuv

**Comment by cboettig** [comment]
apologies, but I am not clear what difficulties you are referring to. your screenshot only shows what I believe are a few harmless warnings during the installation of a package that is being compiled from source.  If your machine is not responding during this process, you might need to confirm it has sufficient RAM.

**Comment by samos999** [comment]
Hi , problem solved . 
I had not enough RAM to install this package.
