### ISSUE TITLE
Request: Remove the VOLUME command from the rstudio Dockerfile

### ISSUE THREAD

**Issue by summerswallow-whi** [rocker-org/rocker-versioned#195]
I've got a situation where I'm bind mounting /home/rstudio. The VOLUME kitematic command is producing a directory in /home/rstudio which is causing confusion to our users who are statisticians and are not tech saavy. There is no way to remove it after the fact without granting the docker container privileges which can expose vulnerabilities. 

In order for me to securely remove the directory, I have to copy the Dockerfile and remove the line and build it myself. This runs the risk of missing updates you might have to the container.

Until such day docker implements an "UNVOLUME" command, it seems to me it is far easier for kitematic users to create a simple Dockerfile
`FROM rocker/rstudio
VOLUME /home/rstudio/kitematic`
to get what they need than to make the rest of use copy the Dockerfile and delete the line VOLUME line.

If you can think of another work around I'm happy to try.

**Comment by cboettig** [comment]
Thanks for the report.  Yeah, we could probably deprecate the use of kitematic, not sure if we have many Kitematic users and it is annoying to have that volume there

**Comment by summerswallow-whi** [comment]
Its easy enough two create a two line Dockerfile to put it back in.
Very difficult to remove.

**Comment by cboettig** [comment]
ok, will do starting with the R-4.0.0 release and going forward. thanks again.
