### ISSUE TITLE
rstudio image with user id 150 not working

### ISSUE THREAD

**Issue by behrica** [rocker-org/rocker-versioned#202]
I try to use the rstudio image on a version of Arch Linux on which my user id 150.

I had a very hard time to get this working until I discovered that the image has not foreseen to work with user ids < 500,
because it hardcodes the minimum user id in the rstudio configuration to be 499:
(in case of id < 1000)

```
auth-minimum-user-id=499 >> /etc/rstudio/rserver.conf
```

I needed to change the userconf.sh and rebuild the image to get it work.

In this situation, I got the error message , the "docker run" started sucessfully,
but I could just not connect to 8787.

I seems that an uid of 150, should be avoided, see here:

https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-Core-generic/LSB-Core-generic/uidrange.html

I am not sure, why I have the id of 150...

**Comment by behrica** [comment]
I figured out, why I have an uid of 150.

I followed this website https://guyrobottv.wordpress.com/2019/01/17/running-arch-linux-on-microsoft-azure-in-2019/

to create a Arch Linux VM for Azure. And in there a user with uid 150 is created, which is probably not a good idea.

Maybe it should just be better documented that the rstudio image does not work with uid < 500 , and we could maybe even check this in the parameters USERID and GROUPID

**Comment by eddelbuettel** [comment]
That's a fairly standard topic. "Way back when" system processes had uids < 100, users started at 100.  Well over a decade ago a cutoff of 1000 became more common.

Let's call it "local user error/issue" -- nothing to do here for Rocker -- so closing.
