### ISSUE TITLE
rocker/verse does not come with curl

### ISSUE THREAD

**Issue by 1beb** [rocker-org/rocker-versioned#206]
It looks like some batteries are missing from rocker/verse:latest. Not sure if this is intentional. There are other places where @cboettig has mentioned that `curl` is installed by default (refs #159) : 

Steps to reproduce
```
user@host: ~# docker run -e PASSWORD=<PASS> --name rstudio -p 8787:8787 -d rocker/verse
user@host: ~# docker exec -it rstudio bin/bash
root@83e92e7deb10:/# curl -help
bash: curl: command not found
```

**Comment by cboettig** [comment]
apologies, `libcurl` is available, so you can do curl commands from R (e.g. via the `curl` package).  but yeah, we should probably add the cli `curl` to `verse` as well.  Should be fixed soon, and apologies for the slow reply.

**Comment by 1beb** [comment]
No problem. I can submit a PR if you point me to the file that needs to be updated. I think it would just be a matter of adding `curl` to https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/latest.Dockerfile#L23 it looks like devel-san already has it.

**Comment by cboettig** [comment]
fixed
