### ISSUE TITLE
R-4.0 ?

### ISSUE THREAD

**Issue by nturaga** [rocker-org/rocker-versioned#208]
Hi,

I was wondering when the new R-4.0-alpha rocker/r-ver and rocker/rstudio images will come out? 

Best,

Nitesh

**Comment by cboettig** [comment]
yup, just tickled the build with your patch so will just take a bit to propagate.  

But note for the actual R 4.0.0 release, we'll be doing a significant upgrade on the versioned stack. In particular:

- We're moving to an Ubuntu-LTS based image (likely starting at 20.04)
- We'll have GPU-flavored (cuda) versions of the stack, including dedicated ML images
- The stack should be more modular

 See https://github.com/rocker-org/rocker-versioned2 and https://hub.docker.com/rockerdev for source and test images.

**Comment by nturaga** [comment]
Hi @cboettig ,

Sorry to broach this again, any sense on when R-4.0 will be available? Parts of our community are wondering if it makes sense to build a temp image with R-4.0 before rocker has them made available.

Best,

Nitesh

**Comment by cboettig** [comment]
@nturaga Temp images are already available and have been for a little while over at https://hub.docker.com/u/rockerdev.  

I'm aiming to have most of the images up by later today over on the official rocker side, though they may see a few tweaks after that while we sort out any bugs.  

This release switches to Ubuntu, and with Ubuntu 20.04 (focal) being released only the day before R 4.0.0, a lot of downstream sources we use haven't fully propagated to Ubuntu 20.04.  (for instance, ubuntugis PPAs are still not available for 20.04, nor are nvidia cuda docker images.  We'll probably launch without these on 20.04, now that most other pieces are live).  

We will probably also have images that build on the older Ubuntu 18.04 (bionic) base as well, which will include that in the tag (`4.0.0-ubuntu18.04` -- you'll see it on many of the rockerdev images) as well as 20.04 images.  


Any feedback/testing on the rockerdev images would be great.  This is obviously a bigger shift than usual, and will have a more detailed documentation of the changes to come soon after, but most things should work identically to before.

**Comment by nturaga** [comment]
Thanks for the reply @cboettig. This is helpful. I'll be testing out a few images, and i'll make sure to get some feedback on this.

**Comment by seandavi** [comment]
> Thanks for the reply @cboettig. This is helpful. I'll be testing out a few images, and i'll make sure to get some feedback on this.

Same here. Thanks a bunch, @cboettig.

**Comment by nturaga** [comment]
Hi @cboettig 

As promised, here is some feedback, when I mount a volume on to the rstudio user, the permissions seem to be an issue to the mount volume

```
my-computer:~$ docker run -it -v /home/turaganitesh/tmp-mount:/home/rstudio/mount --user rstudio rockerdev/rstudio:4.0.0-ubuntu18.04 bash
```

As you can see below,

```
rstudio@39fc4c2befd1:~$ pwd
/home/rstudio
rstudio@39fc4c2befd1:~$ ls -al
total 20
drwxr-xr-x 1 rstudio rstudio 4096 May  5 15:12 .
drwxr-xr-x 1 root    root    4096 Apr 30 23:00 ..
drwxr-xr-x 2    1001    1002 4096 May  5 15:11 mount
drwxr-xr-x 3 rstudio rstudio 4096 Apr 30 23:00 .rstudio
```

The **rstudio** user doesn't have permissions to write to that directory `mount`. I will demonstrate below,

```
rstudio@39fc4c2befd1:~$ R

R version 4.0.0 (2020-04-24) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

..... (removing some lines here)

Type 'q()' to quit R.

> .libPaths("mount/")
> .libPaths()
[1] "/home/rstudio/mount"           "/usr/local/lib/R/site-library"
[3] "/usr/local/lib/R/library"
> install.packages('BiocManager')
Installing package into ‘/home/rstudio/mount’
(as ‘lib’ is unspecified)
Warning in install.packages("BiocManager") :
  'lib = "/home/rstudio/mount"' is not writable
Would you like to use a personal library instead? (yes/No/cancel) no
Error in install.packages("BiocManager") : unable to install packages
```

As you can see I do not have write privileges to this location. It seems that instead of the user, it's giving me a *group id* here, `drwxr-xr-x 2    1001    1002 4096 May  5 15:11 mount`. 

Thoughts on how this can be fixed? It seems we did something of the sorts in the previous debian image as well.

**Comment by nturaga** [comment]
@cboettig Another question for you, where can I find the Dockerfile for `rockerdev/rstudio:R.4.0.0-ubuntu18.04` and I guess it inherits from `rockerdev/r-ver:R.4.0.0-ubuntu18.04`? It'll be very helpful.

**Comment by cboettig** [comment]
@nturaga excellent, thanks for the feedback.  

Dockerfiles are all in https://github.com/rocker-org/rocker-versioned2/tree/master/dockerfiles, a bit messy but hopefully the name scheme is intuitive if not exactly pleasing on the eye.  


Re the permissions, do you not get the same issue with `rocker/rstudio` image?  That looks to me like an issue regarding your host user -- recall docker volume sharing requires that user UIDs match, not names, and it looks like your host is maybe UID  1001 while the default rstudio user is UID 1000.  You should still be able to specify a UID using the env var USERID as before (see https://www.rocker-project.org/use/managing_users/)

**Comment by nturaga** [comment]
> @nturaga excellent, thanks for the feedback.
> 
> Dockerfiles are all in https://github.com/rocker-org/rocker-versioned2/tree/master/dockerfiles, a bit messy but hopefully the name scheme is intuitive if not exactly pleasing on the eye.
> 
> Re the permissions, do you not get the same issue with `rocker/rstudio` image? That looks to me like an issue regarding your host user -- recall docker volume sharing requires that user UIDs match, not names, and it looks like your host is maybe UID 1001 while the default rstudio user is UID 1000. You should still be able to specify a UID using the env var USERID as before (see https://www.rocker-project.org/use/managing_users/)

It does seem to be an issue with my host-user @cboettig. Thanks for pointing it out.

**Comment by cboettig** [comment]
looks like we're all set here.  Bug reports against any 4.0 images always appreciated!  more user-docs still to come...
