### ISSUE TITLE
rstudio from rocker/r-ver:3.5.1

### ISSUE THREAD

**Issue by NJeanray** [rocker-org/rocker-versioned#212]
Hi,

I've just downloaded Dockerfile from your repo and just made the following modification "FROM rocker/r-ver:3.5.1" to avoid mention it explicitely in the command line each time: 

[Dockerfile.txt](https://github.com/rocker-org/rocker-versioned/files/4552105/Dockerfile.txt)

Dockerfile builds perfectly, but when I want to run it thanks to the following command line : 

`docker run -p 3838:3838 -p 8787:8787 -e ADD=shiny -e PASSWORD=mypswd -v /c/Users/nj/Documents/myProject:/home/rstudio/myproject rstudio/myproject`

It gives me the following error message : 

![image](https://user-images.githubusercontent.com/4158621/80605417-560ed800-8a33-11ea-99ac-7f88ad8127aa.png)

Do you have an idea on where it can come from ?
Also, is it possible to customize this Dockerfile to add specific R packages (+ specific versions) ? 

Thanks in advance !

**Comment by cboettig** [comment]
Hi, it's not really clear what you are asking or what you are trying to do. 

Yes, you can customize Dockerfiles and add packages.  The pre-built dockerfiles in this repo might give you some ideas.  If you are just looking to run rstudio in a container, maybe try the the `rocker/rstudio` image.  

best of luck and feel free to re-open here if need be!

**Comment by NJeanray** [comment]
Thanks for your answer !

So I did customize some Dockerfiles from rocker and built it successfully. 
However, when I try to run it, I get systematically the error message mentionned above.
I'm working on Windows 7, and I can't understand what's wrong.
Do you have an idea on why I'm not able to run containers from my image ?

Thanks in advance,

Best regards

**Comment by cboettig** [comment]
@NJeanray Before you go down the road of customization, I suggest you verify that you can run the current, uncustomized Docker images successfully,  e.g as described at https://www.rocker-project.org/ :

```
docker run -e PASSWORD=yourpassword --rm -p 8787:8787 rocker/rstudio
```

I'm sure you can understand that we cannot really guess what your issue might be when all that you have told us is "I customized some Dockerfiles and now they don't work".  You may also consider posting on stackoverflow for general help as this doesn't sound like it is a bug in our images.
