### ISSUE TITLE
TeX missing in rocker/verse:latest / 4.0.0

### ISSUE THREAD

**Issue by dstolpmann** [rocker-org/rocker-versioned#215]
Hi,
the latest version of the rocker/verse image (4.0.0) seems to miss all TeX programs. 

This might be caused by only installing the .deb package of tinytex in https://github.com/rocker-org/rocker-versioned2/blob/master/scripts/install_verse.sh, which is only a couple of KBs in size and does not contain any binaries. The previous version of the Dockerfile (https://github.com/rocker-org/rocker-versioned/blob/master/verse/latest.Dockerfile) also executes a script to install tinytex, which is missing in the newer version.

Best regards,
dstolpmann

**Comment by cboettig** [comment]
@dstolpmann whoopsies!  That .deb package is a dummy package for tinytex, but `install_verse.sh` should have called `install_texlive.sh` and it didn't.  

(having these as separate modules means it should be easier to add `texlive`/`tinytex` without adding all of verse, but we had some indecision on whether the install_verse.sh should always include texlive.  anyway, should have a fix up soon! thanks for the bug report)

**Comment by dstolpmann** [comment]
I just checked and TeX is now available in rocker/verse:latest.

@cboettig Thank you!
