### ISSUE TITLE
stringi fails to load in 4.0.0

### ISSUE THREAD

**Issue by zdk123** [rocker-org/rocker-versioned#221]
```
> library(stringi)
Error: package or namespace load failed for ‘stringi’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
```

It looks like libicu 60 is needed for stringi, but focal only has version 66 available.

**Comment by eddelbuettel** [comment]
Try [bionic](https://packages.ubuntu.com/bionic/libicu60) 00 found via packages.ubuntu.com.

**Comment by zdk123** [comment]
Sorry for the lack of detail in my original post: I'm running this command in an interactive session in a rocker/tidyverse:4.0.0 container (pulled from[ docker hub](https://hub.docker.com/layers/rocker/tidyverse/4.0.0/images/sha256-5eaac332c53a95f5ca500638055510ef0c173a8bbcbf5071e5c1ec91a44020c0?context=explore)).

The base OS seems to be focal, so I don't expect stringi will work unless version icu60 is re-built from source.

**Comment by eddelbuettel** [comment]
In a shell session in the same container (i.e. not from R) do
1. run `ldd` on the file `ldd /usr/local/lib/R/site-library/stringi/libs/stringi.so`
2. it will identify the same missing library
3. use (maybe install) `wget` or `curl` to download http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu60_60.2-3ubuntu3.1_amd64.deb (from the link I gave)
4. `dpkg -i libicu60_60.2-3ubuntu3.1_amd64.deb` as root
5.  redo step 1; it will now resolve the libicu60 library
6.  In R, you can now do `library(stringi)`.

**Comment by cboettig** [comment]
@zdk123 thanks for the report.  Yup, looks like we will need to stick with the source installs on focal at least until RSPM rolls out for `focal`.

**Comment by cboettig** [comment]
should be fixed since we are now on `focal` RSPMs... (and have been for some time!  sorry for the much belated reply)
