### ISSUE TITLE
lack of olson database on r-ver ubuntu

### ISSUE THREAD

**Issue by greg-botwin** [rocker-org/rocker-versioned#222]
I have been using the R-ver Ubuntu image for analysis and have found incompatibility with `readr` due to the lack of an Olson database. I was surprised that the preceding stack r-ver:4.0.0 worked fine. 

Would you consider adding an Olson database to this stack?

Olson Database found on R-ver
```
docker run --rm -ti rocker/r-ver:latest Rscript -e 'OlsonNames()'
  #[1] "Africa/Abidjan"                   "Africa/Accra"                    
  #[3] "Africa/Addis_Ababa"               "Africa/Algiers" 
  #...
```

Olson Database found on r-ver:4.0.0
```
docker run --rm -ti rocker/r-ver:4.0.0 Rscript -e 'OlsonNames()'
  #[1] "Africa/Abidjan"                   "Africa/Accra"                    
  #[3] "Africa/Addis_Ababa"               "Africa/Algiers" 
  #...
```

Olson Database **NOT** found on r-ver:4.0.0-ubuntu18.04
```
docker run --rm -ti rocker/r-ver:4.0.0-ubuntu18.04 Rscript -e 'OlsonNames()'
 #character(0)
 #Warning message:
 #In OlsonNames() : no Olson database found
```

I appreciate your help and your efforts in creating this amazing resource. 
Thanks

**Comment by eddelbuettel** [comment]
That's likely package `tzdata`.

**Comment by cboettig** [comment]
@greg-botwin Thanks.  Please note that `rocker/r-ver:latest` == `rocker/r-ver:4.0.0` == `rocker/r-ver:4.0.0-ubuntu20.04`, i.e. it is running the current Ubuntu LTS release already.  

Yeah, I know we need better docs on this, we're still working on that part of the transition!  

We will likely phase out the `ubuntu-18.04` tags for 4.0.0 -- these were to support some legacy issues that don't look to be necessary.  `rocker-versioned` has always tracked `debian-stable` previously, so we are hoping to simply track the current `ubuntu` LTS now that we have Ubuntu based images.  again apologies we haven't been great at communicating these changes yet!
