### ISSUE TITLE
Modify page elements

### ISSUE THREAD

**Issue by takeMeFlyToAir** [rocker-org/rocker-versioned#224]
hello，I want to modify the elements in the page, such as removing the "export" button. How to implement this?

[如图所示](https://imgchr.com/i/tOY4Jg)

**Comment by eddelbuettel** [comment]
I am sorry what which _page_ are you talking about, and what is the relationship of that page to the Rocker Project's versioned stack?

**Comment by takeMeFlyToAir** [comment]
> I am sorry what which _page_ are you talking about, and what is the relationship of that page to the Rocker Project's versioned stack?
> 
> If this is about _changing RStudio_ then no, sorry, we don't do that. It's source is [available here](https://github.com/rstudio/rstudio).

thanks,my intention is to change rstudio, since you don't do that, so I can look rstudio source, always thank you

**Comment by eddelbuettel** [comment]
Sure, it is open source.  Just respect the license.  Good luck!
