### ISSUE TITLE
Hard-coded `PATH` in `Renviron` causes unexpected behaviour.

### ISSUE THREAD

**Issue by southworthy** [rocker-org/rocker-versioned#225]
The root of the issue is this line, present in a number of Dockerfiles:

https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/3.6.3.Dockerfile#L56

```
&& echo "PATH=${PATH}" >> /usr/local/lib/R/etc/Renviron \
```

What happens is, if the user sets the `PATH` variable before starting `R`, the new `PATH` variable will not be reflected in the R session. Example output below (from a container based off `rocker/verse:3.5.1`):

```
root@51ebbcea3e4c:/home/rstudio# echo "$PATH" | tr ':' '\n'
/opt/miniconda3/bin
/usr/lib/rstudio-server/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/opt/TinyTeX/bin/x86_64-linux/
/home/rstudio/bin
root@51ebbcea3e4c:/home/rstudio# R --slave -e 'cat(Sys.getenv("PATH"))' | tr ':' '\n'
/usr/lib/rstudio-server/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/opt/TinyTeX/bin/x86_64-linux/
root@51ebbcea3e4c:/home/rstudio#
```

As you can see, the `PATH` as seen in the shell is not the same as the one seen in the R session.

I guess I should note; the wider context here is I was trying to invoke a Python script, using Python 3.7 installed from Miniconda. Since the `PATH` was getting overwritten, the `python3.7` binary would fail to be found when I attempted to invoke it with `system2`.

As a workaround, I just added the following to my `Dockerfile`:

```
RUN sed -i 's/^PATH=/#PATH=/' /usr/local/lib/R/etc/Renviron
```

But I'm not really sure what a proper "fix" would entail. Naively, I would just say "remove the line from the Dockerfiles", but again, not sure.

Below is a quick listing of the files I could find with this issue in them:

```
rstudio/3.1.0.Dockerfile:49:12:
rstudio/3.2.0.Dockerfile:49:12:
rstudio/3.2.5.Dockerfile:49:12:
rstudio/3.3.0.Dockerfile:49:12:
rstudio/3.3.1.Dockerfile:48:12:
rstudio/3.3.2.Dockerfile:48:12:
rstudio/3.3.3.Dockerfile:48:12:
rstudio/3.4.0.Dockerfile:52:12:
rstudio/3.4.1.Dockerfile:52:12:
rstudio/3.4.2.Dockerfile:52:12:
rstudio/3.4.3.Dockerfile:52:12:
rstudio/3.4.4.Dockerfile:52:12:
rstudio/3.5.0.Dockerfile:52:12:
rstudio/3.5.1.Dockerfile:54:12:
rstudio/3.5.2.Dockerfile:56:12:
rstudio/3.5.3.Dockerfile:64:12:
rstudio/3.6.0.Dockerfile:60:12:
rstudio/3.6.1.Dockerfile:60:12:
rstudio/3.6.2.Dockerfile:56:12:
rstudio/3.6.3.Dockerfile:56:12:
rstudio/userconf.sh:12:7:echo
verse/3.4.3.Dockerfile:72:12:
verse/3.4.4.Dockerfile:72:12:
verse/3.5.0.Dockerfile:73:12:
verse/3.5.1.Dockerfile:73:12:
verse/3.5.2.Dockerfile:76:12:
verse/3.5.3.Dockerfile:76:12:
verse/3.6.0.Dockerfile:76:12:
verse/3.6.1.Dockerfile:87:12:
verse/3.6.2.Dockerfile:63:12:
verse/3.6.3.Dockerfile:64:12:
```

**Comment by cboettig** [comment]
@southworthy thanks, PATH is a tricky issue. RStudio doesn't respect the system PATH at all, but decides to set it's own PATH.  We add path to `.Renviron` to pick up the system path, as this is the only way to ensure a somewhat consistent env var experience across the RStudio and cli interface.  It is unfortunate that RStudio's R console behaves differently from the CLI console with respect to environmental variables (including PATH), but that is out of our scope.  

Note that you are always able to write a user-level (`~/.Renviron`) or project level `.Renviron` overriding the global one, where you can set a different PATH.  

HTH

**Comment by southworthy** [comment]
Hmmm, yeah that is tricky. We run our development environments off the `rocker` containers, and it's caused confusion for devs in a similar way (e.g. RStudio "terminal" window not behaving the same as the local dev machine "terminal" window).

Hard to say what can be done to fix the issue then I guess; perhaps you could use the "system" `.Rprofile` to set the PATH dynamically on startup? E.g something like

```r
# invoke the user's shell
user_path = system2("su --login rstudio -c 'echo $PATH'", stdout = TRUE)

# set PATH to be the same as the user's PATH
Sys.setenv("PATH", user_path)
```

^won't work verbatim; seems something else is missing (probably one of `~/.profile`, `~/.bash_profile`, `~/.bashrc` or whatever is not being sourced?)

```
root@19d06de9b47a:/home/rstudio# echo $PATH
/opt/miniconda3/bin:/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/TinyTeX/bin/x86_64-linux/:/home/rstudio/bin
root@19d06de9b47a:/home/rstudio# R --quiet
> Sys.getenv("PATH")
[1] "/usr/lib/rstudio-server/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/TinyTeX/bin/x86_64-linux/"
> system2("su", "--login root -c 'echo $PATH'", stdout = TRUE)
[1] "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

Possibly on the right track though....

**Comment by southworthy** [comment]
(dumping `sessionInfo()`)

```
root@18950ca0a07d:/home/rstudio# R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Packrat mode on. Using library in directory:
- "/home/rstudio/packrat/lib"
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.19.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=C
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    packrat_0.5.0
```

**Comment by southworthy** [comment]
I think "if you need something on `PATH`, add it to `.Renviron`" is also a valid solution though 👍
