### ISSUE TITLE
rocker/rstudio and shiny integration

### ISSUE THREAD

**Issue by zcatav** [rocker-org/rocker-versioned#226]
Hi,
I'm using rstudio and shiny container images from 'docker run -d -p 3838:3838 -p 8787:8787 -e ADD=shiny -e PASSWORD=yourpasswordhere rocker/rstudio' .
Rstuio runs as expected but I cant use shiny server. When I invoke localhost:3838 a few different errors occur: 

This site can’t be reachedThe webpage at http://localhost:3838/ might be temporarily down or it may have moved permanently to a new web address.
ERR_SOCKET_NOT_CONNECTED

or

This site can’t be reached
The connection was reset.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET

or

This page isn’t workinglocalhost didn’t send any data.
ERR_EMPTY_RESPONSE

Shiny is loaded at rstudio site and when try run a shiny app rstudio 

> shiny::runApp()
Loading required package: shiny

Listening on http://127.0.0.1:6256

respond like this, open a new browser page. App not runs in shiny server.

What is problem? How can I run shiny apps in shiny server?
Thanks in advance.

**Comment by noamross** [comment]
Starting with images from R 4.0.0 the `ADD=` syntax for installing Shiny is no longer supported.  Instead, we have provided in the images modular install scripts for Shiny (as well as everything else!) to make in easier to customize images to your liking.  Instructions for installing Shiny on top of RStudio or any other image can be found here: https://github.com/rocker-org/rocker-versioned2/tree/add-README#modifying-and-extending-images-in-the-new-architecture

**Comment by zcatav** [comment]
Hi,
Thanks for your attention and clarification.

Zeki Çatav
zekicatav.com

25 Haz 2020 Per 02:59 tarihinde Noam Ross <notifications@github.com> şunu
yazdı:
