### ISSUE TITLE
Run RStudio as user root

### ISSUE THREAD

**Issue by stubclan** [rocker-org/rocker-versioned#228]
I am having issue with adding Volume mount in Kubernetes. 

> Kubernetes mounts the volume path as a root user where user rstudio does not have write permission.

> In order to solve that I want to run RStudio as user root. I can see there's instruction on how to run container with root permission. `docker run -d -p 8787:8787 -e ROOT=TRUE -e PASSWORD=yourpasswordhere rocker/rstudio`

> But how do I convert this to a Dockerfile command so I can run RStudio with user root?

**Comment by cboettig** [comment]
Note that `-e ROOT=TRUE` is just an environmental variable, I believe you can set that at runtime in your kubernetes without writing a custom Dockerfile.  (Note that this gives the `rstudio` user sudo permissions, it doesn't make RStudio run as the user `root`).  

Also, while I don't use Kubernetes at the moment, I strongly suspect you can mount to a different volume other than a root-owned one, including mounting a separate volume container etc.
