### ISSUE TITLE
Linux distro of r-ver:latest changed to Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by Fpadt** [rocker-org/rocker-versioned#229]
Hi,

First of all thanks for this great work.

Just for my understanding I noted that till r-ver:3.6.3 Debian 10 (buster) was used and it seems that for r-ver:latest ubuntu 20.04 LTS is used. I couldn't find anything of this change in the  documentation, might be related to the R version 4.x

I checked this github repository and found only dockerfiles for r-ver till 3.6.3. In the rocker-org/rocker-versioned2 I found the r-ver 4.x docker files. Is Debian abandoned?

many thanks in advance

**Comment by noamross** [comment]
Hi @Fpadt.  There are a number of architectural changes starting with R 4.0.0 so those images are now built and documented at https://github.com/rocker-org/rocker-versioned2.  We just added a note and link in the README here and across the other `r-ver` based repositories, and are working on the best way to make sure the information migrates to Docker Hub.

**Comment by Fpadt** [comment]
superb many thanks noam just found the readme. 
if possible please add a line to the rocker project website https://www.rocker-project.org/images/ if possible
(do understand that it is a lot of maintenance, many thanks again)

**Comment by cboettig** [comment]
Thanks @Fpadt .

Also just adding for the record in case anyone doesn't click through:  from 4.0.0 on, rocker-versioned images (`rocker/r-ver`, `rocker/rstudio`, `rocker/tidyverse`, `rocker/verse`, `rocker/geospatial`, `rocker/binder`, `rocker/shiny`, `rocker/shiny-verse`) are to based on the *latest* Ubuntu LTS, i.e. Ubuntu 20.04.  

Images previously based on debian will remain so.  (Also we need to update: [VERSIONS.md](https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md)
