### ISSUE TITLE
Is there any way to show rstudio in iframe?

### ISSUE THREAD

**Issue by Vinsmoke66** [rocker-org/rocker-versioned#233]
Hello, I want to use rstudio in iframe, can you help me?
when I add www-frame-origin=http://ip:port/ in /etc/rstudio/rserver.conf, it doesn't work and we can see:
Refused to frame 'http://ip:port/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors http://ip:port/".

**Comment by cboettig** [comment]
nope, I don't think so.  This would be an RStudio issue, not a rocker issue though, so they could answer best.
