### ISSUE TITLE
Plotting warning with tidyverse image

### ISSUE THREAD

**Issue by kieran-mace** [rocker-org/rocker-versioned#234]
start image:

```
docker run --rm -e PASSWORD=test -p 8787:8787 rocker/tidyverse
```

go to `localhost:8787` and sign in

run code to generate warning:

```
plot(1:10)
```

warning:
```
Warning message:
In grDevices::grSoftVersion() :
  unable to load shared object '/usr/local/lib/R/modules//R_X11.so':
  libXt.so.6: cannot open shared object file: No such file or directory
```

**Comment by eddelbuettel** [comment]
No, double slashes in a path get sanitized to single.  I suspect you may not have not have followed the tips for Docker and X11?  We have page in the wiki about it: https://github.com/rocker-org/rocker/wiki/Allowing-GUI-windows

**Comment by cboettig** [comment]
can't reproduce this either.

**Comment by micalevisk** [comment]
I'm getting this error as well with `docker run --rm -e DISABLE_AUTH=true -p 8787:8787 rocker/rstudio:latest` on Ubuntu 20.04. I've solved this by running (on RStudio terminal)

```bash
ls /usr/lib/x86_64-linux-gnu | grep libXtst ## returns nothing

sudo apt update
sudo apt install libxtst6
``` 

(source: https://stackoverflow.com/questions/17355863)

**Comment by eddelbuettel** [comment]
R maintainer for Debian (and hence Ubuntu) here -- running on Ubuntu I do not see this via `ldd` on the X11 module:

```sh
edd@rob:~$ ldd /usr/lib/R/modules/R_X11.so | grep libX
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fc21bee7000)
        libXt.so.6 => /usr/lib/x86_64-linux-gnu/libXt.so.6 (0x00007fc21be7a000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fc21a89c000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fc21a887000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fc219ff0000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fc219fe8000)
edd@rob:~$ 
```

Ditto for the RStudio binaries for the nightly I am running.

Also, a `.deb` usually does not build from a (detected) shared library is missing.  So it must be tickled by something ... slightly different code path or setup.
