### ISSUE TITLE
Can not access Rstudio trough localhost since 1 week.mv: cannot stat '/etc/rstudio/disable_auth_rserver.conf': No such file or directory

### ISSUE THREAD

**Issue by Sporgelum** [rocker-org/rocker-versioned#239]
My surprise is after saving the image and migrating it to my windows pc and trying to go to it it displays the following screen locked and the message:
R is taking longer than usual to start:
Reload Safe mode Terminate R
![image](https://user-images.githubusercontent.com/39195785/93328227-c15b1a00-f81b-11ea-813b-849be9b0ec14.png)

And the console message is:
`docker run --rm -p 8787:8787 -v /mnt/e/new/smallRNAsDck/dockerDoor/:/home/rstudio r_smallrna_pirnas:4.0.7`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] userconf: executing...
**mv: cannot stat '/etc/rstudio/disable_auth_rserver.conf': No such file or directory**
Skipping authentication as requested
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

The file which is asking for,**disable_auth_rserver.conf**, i tried to copy it from rocker-versioned github with the lines inside but still not working.

Any solution or bypass, thank you very much.

**Comment by cboettig** [comment]
Duplicate of #235.  Yes, RStudio's recent release broke disable_auth, it'll be fixed soon.  Meanwhile, please just supply a dummy password and use that to log in.

**Comment by Sporgelum** [comment]
Thank you very much!
