### ISSUE TITLE
Loading Rdata/rds breaks R session

### ISSUE THREAD

**Issue by eElor** [rocker-org/rocker-versioned#240]
I'm working on an HPC cluster with two different R sessions (both with R version 4.0.2) -- one from Anaconda (OS: fedora) and the other from a (charliecloud) container running rocker/tidyverse (OS: debian). The one in my conda env is used for jobs send to the Slurm Workload Manager; the one from the rocker container to interactively look at the results produced by the Slurm jobs. Recently, all attempts to load any Rdata or rds files from within an RStudio server session fail and make the R session crash ('R session error: The previous R session was abnormally terminated due to an unexpected crash'). I don't have such a problem, when loading the data from RStudio in Windows, so the problem should come either from charliecloud or the rocker/tidyverse container.

**Comment by eddelbuettel** [comment]
A reproducible example and an rds file triggering a shutdown would help.  R Core will likely (and with reason) wave their hands, it is not clear how reading a file can lead to a shutdown.   You appear aware that the rds format changed from 2 to 3 recently and I presume you took care to ensure that compatible versions are used -- only using 4.0.2 everywhere would in fact ensure that.

**Comment by eElor** [comment]
I just created an Rdata file in a similar way as the ones I have trouble with. They are successfully loaded into the rocker container... Unfortunately, I cannot share the problematic files, since they contain sensitive data 😟 
Yes, R versions should not be the problem, since I am using 4.0.2 for both cases.

**Comment by cboettig** [comment]
One thing would be to confirm your server is not running out of memory in trying to read a potentially large data file?  Try monitoring server statistics on your machine when the crash happens, and if possible, try testing using the rocker container locally or on another machine.  Please re-open if there's an example we can run to help.
