### ISSUE TITLE
rocker/r-ver points to now defunct mran mirror

### ISSUE THREAD

**Issue by JSchoenbachler** [rocker-org/rocker-versioned#241]
About 17 hours ago, Microsoft updated their mran mirrors to point to the cran links instead of mran:

https://github.com/Microsoft/microsoft-r-open/releases/tag/MRO-4.0.2

This is causing some package installation errors when using the image in CircleCI. Could you change the line in your Dockerfile from
`else MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE}; fi \`
to
`else MRAN=https://cran.microsoft.com/snapshot/${BUILD_DATE}; fi \`

**Comment by cboettig** [comment]
Yup, just noticed this today as well.  

BTW, if you're seeing this you're probably running old rocker images.  That's fine if you're trying to reproduce old stuff, but otherwise you might want to update to the newer 4.x series (which use RStudio RSPM instead of MRAN)

**Comment by JSchoenbachler** [comment]
Okay gotcha. Thanks!

**Comment by JSchoenbachler** [comment]
As another update, it looks like MS fixed this on their own end by just redirecting from the `mran.microsoft` to `cran.microsoft` so this doesn't seem to throw an error anymore.
