### ISSUE TITLE
rJava newly failing to install 

### ISSUE THREAD

**Issue by AARON4744** [rocker-org/rocker-versioned#243]
I want to install rJava in R and I installed java se and jdk previously,but always failed .  I'd love some help 

make: Entering directory '/cygdrive/c/Users/JHY/AppData/Local/Temp/Rtmp0yxqky/R.INSTALL12004b6d4675/rJava/src/jvm-w32'
D:/tools/R/Rtools/mingw_64/bin/dlltool --as D:/tools/R/Rtools/mingw_64/bin/as  --input-def jvm64.def --kill-at --dllname jvm.dll --output-lib libjvm.dll.a
D:/tools/R/Rtools/mingw_64/bin/gcc  -O2 -c -o findjava.o findjava.c
D:/tools/R/Rtools/mingw_64/bin/gcc  -s -o findjava.exe findjava.o
make: Leaving directory '/cygdrive/c/Users/JHY/AppData/Local/Temp/Rtmp0yxqky/R.INSTALL12004b6d4675/rJava/src/jvm-w32'
Find Java...
  JAVA_HOME=C:/PROGRA~1/Java/jdk-15
=== Building JRI ===
  JAVA_HOME=C:/PROGRA~1/Java/jdk-15
  R_HOME=d:/tools/R/R-3.5.3
JDK has no javah.exe - using javac -h . instead
Creating Makefiles ...
Configuration done.
make -C src JRI.jar
make[1]: Entering directory '/cygdrive/c/Users/JHY/AppData/Local/Temp/Rtmp0yxqky/R.INSTALL12004b6d4675/rJava/jri/src'
C:/PROGRA~1/Java/jdk-15/bin/javac -h . -d . ../RList.java ../RBool.java ../RVector.java ../RMainLoopCallbacks.java ../RConsoleOutputStream.java ../Mutex.java ../Rengine.java ../REXP.java ../RFactor.java ../package-info.java
..\Rengine.java:120: 错误: 受限标识符 'yield' 的用法无效
        while (!alive && !died) yield();
                                ^

make[1]: *** [Makefile.all:41: org/rosuda/JRI/Rengine.class] Error 1
make[1]: Leaving directory '/cygdrive/c/Users/JHY/AppData/Local/Temp/Rtmp0yxqky/R.INSTALL12004b6d4675/rJava/jri/src'
make: *** [Makefile.all:19: src/JRI.jar] Error 2
**** WARNING: JRI could NOT be built
Set IGNORE=1 if you want to build rJava anyway.
ERROR: configuration failed for package 'rJava'
* removing 'd:/tools/R/R-3.5.3/library/rJava'
In R CMD INSTALL
Warning in install.packages :
  installation of package ‘rJava’ had non-zero exit status

**Comment by eddelbuettel** [comment]
This has nothing to do with Rocker as you appear to be installing under Windows directly, so I am closing this.

If you have a bug report for this report, please feel free to reopen.  But do everybody a favor and do not spam unrelated projects.
