### ISSUE TITLE
Expose VOLUME for Kitematic users?

### ISSUE THREAD

**Issue by andrewheiss** [rocker-org/rocker-versioned#25]
Before depending on rocker-versioned, rocker images included a `VOLUME` instruction to expose `/home/rstudio` for Kitematic users (see https://github.com/rocker-org/rocker/commit/732378c424030567d75d8dacd9b4a6315a91da52, for instance). This instruction is gone now in rocker-versioned. Is this by design? Can `VOLUME` be added back in, or is it best to just use the various rocker images from terminal?

**Comment by cboettig** [comment]
I always found the lack of configuration options in Kitematic rather perplexing, but yeah, this seems reasonable.  I think perhaps we should make it a specific sub-directory (e.g. `/home/rstudio/kitematic` maybe?) rather than `/home/rstudio`, to avoid potential conflicts.  Sound good?

**Comment by andrewheiss** [comment]
Yeah, that sounds great. 

I guess users could do it on their own by making their own Dockerfiles with "FROM rocker/tidyverse:latest" or whatever at the top, but having it in the core Rocker files helps, I think.

**Comment by cboettig** [comment]
agreed; anyone wanting to use the Kitematic GUI probably doesn't want to have to write custom dockerfiles.  I've added this to `rstudio` (does the base R version work from Kitematic? e.g. does it open an R terminal for you like it does with `docker run`, or does it not do anything?  I know Kitematic works with rstudio so I put it in starting at that image)

**Comment by andrewheiss** [comment]
It looks like it puts the R startup message in the container logs, but that's all. The actual program is only accessible from the CLI (i.e. after typing `docker exec -i -t r-base /bin/bash`)

![image](https://cloud.githubusercontent.com/assets/73663/24121498/d7f3148c-0d8e-11e7-9328-2b9412f030a6.png)

**Comment by cboettig** [comment]
Thanks for confirming, that's what I figured.  So it's fine we don't bother exposing a kitematic VOLUME until the rstudio part of the stack.
