### ISSUE TITLE
Can not build image on M1 Mac

### ISSUE THREAD

**Issue by k-hashimoto** [rocker-org/rocker-versioned#250]
Hi guys,

I couldn't run ` rocker/rstudio` docker image on M1 Mac.
<img width="912" alt="スクリーンショット 2021-01-10 23 03 18" src="https://user-images.githubusercontent.com/12578508/104140555-41257980-53f5-11eb-965b-6357c7e959d3.png">

So I tried to build image from Dockerfile (cd to rocker-versioned/rstudio) but...
```
#4 70.23 Setting up liberror-perl (0.17027-2) ...
#4 70.48 Setting up git (1:2.20.1-2+deb10u3) ...
#4 70.82 Processing triggers for libc-bin (2.28-10) ...
#4 72.48 dpkg: error processing archive rstudio-server-1.2.5042-amd64.deb (--install):
#4 72.48  package architecture (amd64) does not match system (arm64)
#4 72.57 Errors were encountered while processing:
#4 72.57  rstudio-server-1.2.5042-amd64.deb
------
```

So the only solution is to wait for  `rstudio-server-xxxxx-arm64.deb`   ?

**Comment by eddelbuettel** [comment]
Correct.  The Dockerfiles generally expect x86_64 binaries.  One exception is rocker/r-base which also gets built as the official r-base for the following architectures:  amd64, arm64v8, ppc64le, s390x.  I don't know a) if/when Debian and Ubuntu will have arm64 binaries and b) if/when RStudio may offer builds.
