### ISSUE TITLE
Use a newer version of dplyr? 

### ISSUE THREAD

**Issue by radiocontrolled** [rocker-org/rocker-versioned#256]
I'm using `rocker/verse:3.6.3`. When I do `sessionInfo()` in an Rscript it tells me I'm getting this version of dyplr: <br/>
`dplyr_0.8.5`. How can I get a newer version of Dplyr? Thanks

This is my dockerfile.

```
FROM rocker/verse:3.6.3 
ENV DEBIAN_FRONTEND noninteractive
ENV TZ GMT

# Install needed R packages
RUN install2.r --error \
    magick \
    ggpubr \
    extrafont \
    gridExtra \
    purrr \
    lubridate \
    jsonlite \
    ggimage 

RUN install2.r --error \
    -r 'http://cran.rstudio.com' \
    dplyr 
```

From my codebuild logs I can see this installs  'http://cran.rstudio.com/src/contrib/dplyr_1.0.5.tar.gz' to `/usr/local/lib/R/site-library/00LOCK-dplyr/00new/dplyr/libs` but I'm not sure how to use this specifc version of dplyer in my R script?

**Comment by cboettig** [comment]
(@radiocontrolled you probably figured this out but just for the record here: old image versions freeze packages by default for reproducibility.  Switch to an image with `latest` tag to get the latest versions (including current R version), or simply change the default `repos` selection in `options()` to use a non-frozen repo.
