### ISSUE TITLE
can not install R packages on rocker/rstudio

### ISSUE THREAD

**Issue by ABanaeiEsfahani** [rocker-org/rocker-versioned#264]
Hello,

I just pulled down the latest version of rocker/rstudio and started working on that. But it seems that I can not install any R package there. Could you please help me with that? Thanks for your support.

Best,
Amir

P.S.
> install.packages("data.table")
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib:
  cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘data.table’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**Comment by ABanaeiEsfahani** [comment]
Sorry, I had forgot to set the environment well. We can close this ticket for now.

**Comment by eddelbuettel** [comment]
Will close.  The active repo for this would have been rocker-org/versioned2.  Please file there next time.
