### ISSUE TITLE
Installing packages that depend on r-base-core

### ISSUE THREAD

**Issue by rstub** [rocker-org/rocker-versioned#38]
With the versioned rocker images one is supposed to install all R packages via CRAN instead of apt. But how about installing other packages that depend on r-base-core? Things like apache2-mod-r-base or postgersql-9.6-plr might be useful to have in a docker image. One solution would be to install a r-base-core-dummy package build via equivs. Here a minimal equivs file:
```
# Source: <source package name; defaults to package name>
Section: misc
Priority: optional
# Homepage: <enter URL here; no default>
Standards-Version: 3.9.2

Package: r-base-core-dummy
Version: 3.4.0
# Maintainer: Your Name <yourname@example.com>
# Pre-Depends: <comma-separated list of packages>
# Depends: <comma-separated list of packages>
# Recommends: <comma-separated list of packages>
# Suggests: <comma-separated list of packages>
Provides: r-base-core
# Replaces: <comma-separated list of packages>
# Architecture: all
# Multi-Arch: <one of: foreign|same|allowed>
# Copyright: <copyright file; defaults to GPL2>
# Changelog: <changelog file; defaults to a generic changelog>
# Readme: <README.Debian file; defaults to a generic one>
# Extra-Files: <comma-separated list of additional files for the doc directory>
# Files: <pair of space-separated paths; First is file to include, second is destination>
#  <more pairs, if there's more than one file to include. Notice the starting space>
Description: Dummy package for r-base-core
 Dummy package for r-base-core
```

Besides installing the package generated from this, I also had to call `ldconfig /usr/local/lib/R/lib`in my tests. It would be great if something along these lines where integrated in the images.

**Comment by cboettig** [comment]
Thanks for the suggestion, that's intriguing. It's not obvious that this trick wouldn't have undesirable side-effects on certain binaries though. I'll defer to @eddelbuettel on that.

In general our advice has been to install such dependencies from source on the version-stable stack.  With Debian's stable releases having a ~ 2 year release cycle, the versions in the apt repos can be quite out-of-date anyway so this issue hasn't seemed pressing.  After all, rocker already provides the `debian:testing` based stack (see rocker-org/rocker repo) where installing recent versions of dependencies directly from the apt-repos just works right out of the box.  

Not trying to dismiss the suggestion though; it would be great if I could better understand your use case here to know why building on `testing`-based stack (or installing from source) isn't sufficient?

**Comment by eddelbuettel** [comment]
I don't know. I don't think too much about the _versioned_ stack, sorry.  Not really my preoccupation.

If you need packages for targeted Debian versions, maybe you need targeted backports. Dunno -- sorry.

**Comment by rstub** [comment]
For me it less an issue of `testing` vs. `stable` but the ability to have *different* versions of R available together with "matching" CRAN packages. That is not offered by the `testing`-based stack. Compiling from source is of course an option. As is installing the virtual package myself.

However, at the moment I am experiencing some weird failures from apache2-mod-r-base, which I want to resolve first.

**Comment by eddelbuettel** [comment]
Well, as the (effective and then also formal) R maintainer for Debian for close to 20 years you get to blame me.  We simply do not allow for parallel concurrent installations of multiple R versions.

**Comment by rstub** [comment]
Guess that's it then. For now I am using the `testing`-based stack.
