### ISSUE TITLE
Knit PDF not working in R-ver:3.3.2

### ISSUE THREAD

**Issue by prashant182** [rocker-org/rocker-versioned#41]
The error message is `framed.sty not found`. Tried to install it by `sudo tlmgr update --self
sudo tlmgr install framed`. It should work, but It didn't.

**Comment by cboettig** [comment]
Are you using the `rocker:verse:3.3.2` image?  Knitting a pdf with RStudio's default pdf document template is working fine for me on that image.  You mention `r-ver` in the title, note that latex isn't installed on the `r-ver` image so knitting to pdf is not going to work.  If you want PDF to work out of the box, please use the `verse` image.

**Comment by prashant182** [comment]
I am sorry, I meant `R-verse` when I said `R-ver`. I will try to remove the container and then try again. If I still have the same error, I will post a detailed error log.

**Comment by cboettig** [comment]
Okay, closing, but re-open if you can reproduce the error and include the details.
