### ISSUE TITLE
rstudio image: not able to install package from source

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker-versioned#46]
I updated from version 3.3.3 to 3.4.1 and now I get a modal with the message when I try to install a new package using devtools. Calling the same command in the docker bash works.

> building r package from source requires installation of additional build tools. 

When I click ok it fails without an error message. I am using linux and the rocker image, so all those "additional build tools" should be already installed, right?

**Comment by eddelbuettel** [comment]
What command?

What package?

What container?

Please try to help us help you.

**Comment by inkrement** [comment]
I am using `rocker/verse:3.4.1` to host RStudio Server. I started it, logged into the web-interface and run `devtool::install_github`. Then I got the message that some "additional build tools" are missing, but no info which are missing. When I accept to install them, it stops after downloading the package-source with the following error message:

> Installation failed: Could not find build tools necessary to build clckhs

I connected to the container and checked if typical "build"-packages (e.g., g++, make, build-essentials) are installed and they are. Then I wanted to check error logs, but the /var/log/rstudio-server folder is empty. Most forum posts related to this error message state that the problem is a missing RTools installation, but I use the rocker container and not windows. Any idea what could be the problem?

**Comment by eddelbuettel** [comment]
Beats me.  But I am sure @cboettig will pipe -- those versioned containers are his babies.

**Comment by cboettig** [comment]
Seems to be a recent `devtools` problem, trying to track down just what now. Meanwhile, can you try:

```r
install.packages("remotes")
remotes::install_github(...
```

**Comment by inkrement** [comment]
ok, thanks. Then I'll close this issue here.

**Comment by cboettig** [comment]
Just for the record, see https://github.com/hadley/devtools/issues/1590

basically this is a problem with the RStudio IDE, which `devtools` pings (if RStudio is being used) to detect build tools.  Hopefully should be fixed soon.  Meanwhile, use `remotes::install_github()`, or even just `devtools::install_github()` in CLI R, outside the IDE.

**Comment by cboettig** [comment]
p.s. we've found a workaround the IDE bug, so once the stack rebuilds this should "just work" once more.
