### ISSUE TITLE
MRAN instead of CRAN repository?

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker-versioned#47]
I am wondering if MRAN is set as the default repository or how I can change this behaviour. A new rocker container seems to use MRAN... If not, why can this happen? I mounted a existing home directory to the container, could this be the problem?
```
> install.packages("packrat")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://mran.microsoft.com/snapshot/2017-08-18/src/contrib/packrat_0.4.8-1.tar.gz'
Content type 'application/octet-stream' length 113922 bytes (111 KB)
```

**Comment by inkrement** [comment]
ok, I found the problem. It is set in `/usr/local/lib/R/etc/Rprofile.site`. Is this intended?
![screen shot 2017-08-20 at 20 16 00](https://user-images.githubusercontent.com/604528/29497220-85599074-85e4-11e7-898f-6148e16ea365.png)

**Comment by eddelbuettel** [comment]
What container?   For some (ie "r-ver") is _very much_ on purpose.

Please try to help us help you.

**Comment by inkrement** [comment]
haha... you are right! I am using `rocker/verse:3.4.1`

**Comment by eddelbuettel** [comment]
Please read [the README here](https://hub.docker.com/r/rocker/verse/),

If you want unversioned try `rocker/verse:latest`.

**Comment by inkrement** [comment]
ah. ok thanks
