### ISSUE TITLE
Not able to save changes "No such file or directory"

### ISSUE THREAD

**Issue by inkrement** [rocker-org/rocker-versioned#48]
From time to time I have problems to save open files. I get the error "No such file or directory", then I have to copy all the changes into the clipboard, close the file, reopen it and then it works.

![screen shot 2017-08-22 at 09 05 55](https://user-images.githubusercontent.com/604528/29552919-89091a9c-8719-11e7-83e2-45957c49f56f.png)

I also get some related errors in the console:
```
22 Aug 2017 06:16:11 [rsession-chris] ERROR system error 2 (No such file or directory); OCCURRED AT: rstudio::core::Error rstudio::session::source_database::get(const string&, boost::shared_ptr<rstudio::session::source_database::SourceDocument>) /home/ubuntu/rstudio/src/cpp/session/SessionSourceDatabase.cpp:570; LOGGED FROM: SEXPREC* rstudio::session::modules::r_packages::{anonymous}::rs_getKnitParamsForDocument(SEXP) /home/ubuntu/rstudio/src/cpp/session/modules/SessionRCompletions.cpp:456
22 Aug 2017 06:16:12 [rsession-chris] ERROR system error 2 (No such file or directory); OCCURRED AT: rstudio::core::Error rstudio::session::source_database::get(const string&, boost::shared_ptr<rstudio::session::source_database::SourceDocument>) /home/ubuntu/rstudio/src/cpp/session/SessionSourceDatabase.cpp:570; LOGGED FROM: SEXPREC* rstudio::session::modules::r_packages::{anonymous}::rs_getKnitParamsForDocument(SEXP) /home/ubuntu/rstudio/src/cpp/session/modules/SessionRCompletions.cpp:456
```
Version: rocker/verse:3.4.1

**Comment by cboettig** [comment]
Yeah, I think I've seen this rather rarely too, usually on long-running instances maybe?  Difficult to debug since I haven't found any way to predictably reproduce it.  The console errors look like RStudio library things, and probably should be reported to the RStudio team, they might have more insight.

Do you have any linked local volumes when this occurs?

**Comment by inkrement** [comment]
Yes, I mounted the home directory to persist all changes and you are right, just happens from time to time.

**Comment by cboettig** [comment]
good to know.  Just so I have the log of the relevant details, can you let me know what platform you are using, and in particular, what Docker is using for the "Storage Driver" (see `docker info`).  Could be an RStudio issue, but I'm wondering if this is somehow due to the driver `devicemapper`.  Thanks!

**Comment by inkrement** [comment]
```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 53
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 503.7GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cboettig** [comment]
We've tweaked how RStudio handles file locks a little while back: https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile#L59 which should make this a bit better, but not sure if we can eliminate this entirely (e.g. if container and linked volume are out of sync on file locks).
