### ISSUE TITLE
verse:3.3.1 depends on the tidyverse:latest

### ISSUE THREAD

**Issue by vladpetyuk** [rocker-org/rocker-versioned#49]
The `rocker/verse:3.3.1` is built based on `rocker/tidyverse:latest`.  I think it supposed to be `rocker/tidyverse:3.3.1`. Please ignore it supposed to be the latest tidyverse.

**Comment by cboettig** [comment]
Thanks for catching that, I somehow missed noticing that in merging an earlier PR.  I'll trigger verse:3.3.1 to rebuild on hub now.
