### ISSUE TITLE
[rocker/verse] xelatex not found when building pdf with bookdown

### ISSUE THREAD

**Issue by RLesur** [rocker-org/rocker-versioned#50]
I plan to use `rocker/verse` to build `bookdown` websites with `GitLab Pages` and `GitLab CI` (you can see a demo website [here](https://rlesur.gitlab.io/bookdown-gitlab-pages))   
All work fine with `pdflatex` as `latex_engine`. But, when I try to use `xelatex` instead of `pdflatex`, I get the following error:  
```
sh: 1: xelatex: not found
```

Thanks a lot for your work, Rocker rocks! :metal:

**Comment by eddelbuettel** [comment]
So if _you_ want to do, then maybe _you_ need to build on our containers and extend them with `xelatex` and whatever is needed.

We appreciate you bringing this our attention, but we cannot possibly accomodate _all_ imaginable use cases for _each and every_ CRAN package.

**Comment by RLesur** [comment]
Thanks! I will do that.
