### ISSUE TITLE
Add more Label Schema metadata

### ISSUE THREAD

**Issue by nuest** [rocker-org/rocker-versioned#52]
Could add some more of Label Schema metadata conventions. 

Current state has `license`, `vcs-url`, and `vendor`, see https://github.com/rocker-org/rocker-versioned/blob/58273c594e195e274efcba06043ba27000270784/r-ver/Dockerfile#L3

**Candidates:**

- `org.label-schema.url="https://www.rocker-project.org/"`
- `org.label-schema.vcs-ref="279FA63"` (could be done via build hook, and even help matching an instance to the respective Zenodo archive)
- `org.label-schema.usage="https://www.rocker-project.org/use/"`
- `org.label-schema.version="1.2.3"` (via build hook)
- `org.label-schema.schema-version="1.0"`
- `org.label-schema.docker.cmd` and `docker.params`
  - could be useful for `rstudio` images where there are relevant parameters to set and a port to expose, but certainly depends on the labels being more widespread

As a side note: Label Schema has been "absorbed" into OCI, see https://github.com/label-schema/label-schema.org/issues/33#issuecomment-333123644, so at some point the labels might have to be changed a bit, see https://github.com/opencontainers/image-spec/blob/fc936c78346d017dcdbc6dd220a8ff60675ce3b5/annotations.md#back-compatibility-with-label-schema

**Comment by cboettig** [comment]
PR welcomed :-)

**Comment by eitsupi** [comment]
I think we have achieved this in our latest images.
