### ISSUE TITLE
shiny-server.log not created when using ADD=shiny

### ISSUE THREAD

**Issue by phlogisticfugu** [rocker-org/rocker-versioned#55]
When executing 

> docker run -d -p 3838:3838 -p 8787:8787 -e ADD=shiny rocker/rstudio

as per https://hub.docker.com/r/rocker/rstudio-stable/

The docker container runs daemonized, with no stdout, but the system.d run script
at /etc/services.d/shiny-server/run does not pipe the stdout to the normal /var/log/shiny-server.log location.  This means that all of the shiny server logs go into a black hole, and one cannot see them at all.

proposed solution:
change
> echo '#!/bin/bash' > run && echo 'exec shiny-server' >> run && \

to
> echo '#!/bin/bash' > run && echo 'exec shiny-server > /var/log/shiny-server.log' >> run && \

in the add_shiny.sh files.
Note that when running in non-daemonized mode that the current implementation displays output to the docker host command line, which is nice, but not as useful as running in daemonized mode.

**Comment by cboettig** [comment]
Good idea.  Care to send a pull request?
