### ISSUE TITLE
Unable to install packages from MRAN

### ISSUE THREAD

**Issue by rstub** [rocker-org/rocker-versioned#58]
I am currently unable to install packages without specifying the repository location:
```
$ docker run rocker/r-ver:3.4.2 install2.r codetools
Warning: unable to access index for repository https://mran.microsoft.com/snapshot/2017-10-31/src/contrib:
  Line starting '<!doctype html><html ...' is malformed!
Warning message:
package ‘codetools’ is not available (for R version 3.4.2) 
```

Looking at https://mran.microsoft.com I see that they actually link to https://cran.microsoft.com for actual package content. And indeed the following works:
```
$ docker run rocker/r-ver:3.4.2 install2.r -r https://cran.microsoft.com/snapshot/2017-10-31 codetools
trying URL 'https://cran.microsoft.com/snapshot/2017-10-31/src/contrib/codetools_0.2-15.tar.gz'
Content type 'application/octet-stream' length 12930 bytes (12 KB)
==================================================
downloaded 12 KB

* installing *source* package ‘codetools’ ...
** package ‘codetools’ successfully unpacked and MD5 sums checked
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (codetools)

The downloaded source packages are in
	‘/tmp/downloaded_packages’
```

**Comment by cboettig** [comment]
Thanks for the ping, Microsoft must have changed that URL pretty recently (i.e. today, since `r-ver` image builds nightly and this error now causes that build to fail).  Guess we can update the URL, but seems like something of a bug on Microsoft end...

**Comment by cboettig** [comment]
https://twitter.com/revodavid/status/930202617422274560

**Comment by rstub** [comment]
Thanks. Installing from MRAN works again.

**Comment by cboettig** [comment]
Thanks for letting us know.  Sounds like Microsoft R team was migrating servers and hit a glitch, but were able to quickly resolve it.
