### ISSUE TITLE
SSH RSA key generation issue -- rocker-org/rstudio:3.4.3

### ISSUE THREAD

**Issue by ddurden** [rocker-org/rocker-versioned#67]
When trying to create an SSH RSA key in RStudio ==> Global Options ==> Git/SVN I get an error "/bin/sh: 1: ssh-keygen: not found". I think it may be due to a recent update, as this behavior does not occur when using geospatial or ropensci docker images.

I additionally, checked the terminal and saw the same error.

**Comment by cboettig** [comment]
um, did this ever work on the `rstudio` images?  `ssh` is added in `verse`: https://github.com/rocker-org/rocker-versioned/blob/master/verse/Dockerfile#L33 so `ropensci` and `geospatial` should be getting it from there.

**Comment by ddurden** [comment]
Ah, thanks @cboettig. We were moving from `ropensci` to a lighter image `rstudio`. I checked most of the stack for the call, but I must have missed it. Thanks again.

**Comment by cboettig** [comment]
@ddurden cool, thanks for the kind words!  You might then also enjoy our recent paper specifically on the Rocker project, which I think should be out in R-Journal later this month; preview version here: https://rjournal.github.io/archive/2017/RJ-2017-065/index.html

Yeah, `verse` is meant to be more batteries included for these common things while being a lot smaller than `ropensci`, which has a lot of specialized stuff most folks don't need, as you've probably seen.  Though for a custom small image probably most efficient to add just what you need directly to the base or `rstudio` image.

**Comment by ddurden** [comment]
Nice, I will definitely give it a read. We actually cited your last paper in our paper on developing a DevOps framework for community-based Science software development: [Metzger et al., 2017](https://www.geosci-model-dev.net/10/3189/2017/). You might find it interesting.

**Comment by cboettig** [comment]
will check it out, thanks!

**Comment by jspitzen** [comment]
In case anyone ever comes across this and wants to generate SSH keys, it works to simply extend the image with the `openssh-server` package.
```
FROM rocker/tidyverse

RUN apt-get update && apt-get install -y \
  openssh-server --no-install-recommends
```
