### ISSUE TITLE
Cannot launch terminal in RStudio 1.1.419 (rocker/verse:3.4.3)

### ISSUE THREAD

**Issue by RLesur** [rocker-org/rocker-versioned#70]
Since RStudio 1.1.419, I cannot launch any terminal. I use rocker/verse:3.4.3. 
I test with an older image (rocker/verse:3.4.1 with RStudio 1.1.383), and it works perfectly.

---

**edit**  
Here is info about rocker/verse:3.4.3 image and system:

    IMAGE ID
    c073e6900b7d
    
    Docker version 17.12.0-ce, build c97c6d6

    System:
    Ubuntu 16.04 xenial (x86-64)
    Linux kernel:
    4.4.0-112-generic

**Comment by cboettig** [comment]
@RLesur Are you trying to launch the new in-window terminal (tools->terminal->new terminal)?  
I can't replicate this, working with a fresh pull of `rocker/verse:3.4.3` terminal opens just fine for me in the RStudio pane.  Can you pull and try again? (Include the image hash for & docker version and platform for reference as well if it's still not working.)

**Comment by RLesur** [comment]
@cboettig I pulled a new image (`b065861e9f9e`) and tried to open a new terminal (`Tools > Terminal > New Terminal`) and nothing happened.  
When I select the opened tab terminal (next to the R console), I have no command line:
 
![image](https://user-images.githubusercontent.com/19177171/35933248-60aceb9a-0c3a-11e8-9b72-e9691c20f89f.png)
  
I've also tested `Tools > Shell...` and I cannot open any shell. 

Opening the menu `Tools > Terminal > Terminal Diagnostics...`, I get
![image](https://user-images.githubusercontent.com/19177171/35933589-5a825cd6-0c3b-11e8-88a2-8afc1db50547.png)

I ran my container with:

    docker run --rm -p 8787:8787 b065861e9f9e

Is there any docker options to activate shell? 

---

    IMAGE ID
    b065861e9f9e

    Docker version 17.12.0-ce, build c97c6d6

    System:
    Ubuntu 16.04 xenial (x86-64)
    Linux kernel:
    4.4.0-112-generic

**Comment by cboettig** [comment]
Haven't seen this one before, it my instance it just opens. (sometimes there is a few second delay when clicking to the terminal tab before the command prompt appears) 

`Tools -> Shell` doesn't do anything for me either, I assume it's deprecated.

I assume you've tried `Tools->Terminal->new terminal` as well?

**Comment by RLesur** [comment]
Yes, I have. I also tried to modify the terminal settings in `Global options`.

**Comment by cboettig** [comment]
weird. I'm on Docker 18.01.0-ce, could be it but would surprise me.   (I'm also on ubuntu 16.04.03, 4.4.0-109 kernel, basically same as you)

**Comment by RLesur** [comment]
is there any docker option you use for running the container?

**Comment by cboettig** [comment]
nope, just `docker run --rm -p 8787:8787 rocker/rstudio:3.4.3`

**Comment by RLesur** [comment]
I just found: I deactivated all my firefox extensions and retrieved the terminal panel. 
I close the issue. Sorry for the inconvenience.

**Comment by cboettig** [comment]
Ha! glad it's resolved.  Will have to remember to include disabling browser plugins next time we're debugging rstudio server behavior.  anyway, thanks for the report and the follow-up on resolution
