### ISSUE TITLE
File "multirow.sty" not found and cannot be installed with package manager

### ISSUE THREAD

**Issue by mcenno** [rocker-org/rocker-versioned#73]
Hello,

I hope this is the correct place to address this issue.

I'd like to generate a Rmarkdown document with bookdown and kable tables. HTML output works fine, but PDF output does not:

`This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! LaTeX Error: File 'multirow.sty' not found.`

This file is part of the package `texlive-latex-extra`, but installation of this package (and its dependencies) fails with some obscure errors, which appear as yet to be unresolved:

`E: Sub-process /usr/bin/dpkg returned an error code (1)
Setting up texlive-base (2016.20170123-5) ...
Can't use string ("2") as an ARRAY ref while "strict refs" in use at /usr/bin/tl-paper line 112.
`

See https://www.tug.org/pipermail/tex-live/2015-December/037551.html for details on this error.

My understanding is that you're not using the Debian TeX packages but others. Would it be possible to install this file into the container so kable can produce PDF output?

Cheers,

Enno

**Comment by eddelbuettel** [comment]
Which container were you using?  '2016.20170123' hints at something older.

**Comment by mcenno** [comment]
I can't really answer - here is my Dockerfile:

FROM rocker/verse
RUN apt-get update && apt-get install -y aptitude
RUN aptitude -f install
RUN aptitude install -y texlive


I included aptitude here because it is known (to my understanding) that it is a bit better at resolving conflicts and dependencies. It didn't help, though.

So I think I'm using a current image.

Enno

**Comment by eddelbuettel** [comment]
a) `aptitude` being better is hearsay from a decade+ ago; these days all apt programs use the same backend AFAIK
b) I never had anything missing from texlive, or installation issues, so beats me.
c) Didn't Carl switch versefrom texlive to tinytex (for better or worse) so dropping texlive on top may have issues.
d) In any event, would this not appear to be an error in _your_ container rather than ours?

**Comment by mcenno** [comment]
a) Maybe that's true, but my personal, very subjective, experience is that I've resolved more conflict situations with aptitude than with apt-get, but that's unimportant here. I just wanted to explain the rationale behind the Dockerfile.

b) Too bad

c) Who is Carl? I've seen somewhere that indeed texlive in rocker/verse is not using official Debian repositories, so I'm inclined to agree

d) This I don't understand - with my Dockerfile above am I not using your container as a starting point?

Apologies for my ignorance but I have started with Docker not too long ago.

Enno

**Comment by eddelbuettel** [comment]
> am I not using your container as a starting point?

Yet the bug seems to be caused by your transformations thereafter.

Carl is the good Prof Boettiger and the other half of this project which happens to look after *verse.

**Comment by cboettig** [comment]
```
tlmgr update --self
tlmgr install multirow
```

see https://yihui.name/tinytex/

**Comment by IntiQuan** [comment]
Same issue ... despite closed subject. Not very helpful
