### ISSUE TITLE
texinfo for verse images with tinytex

### ISSUE THREAD

**Issue by noamross** [rocker-org/rocker-versioned#77]
`texinfo` is needed to build R pdf manuals but seems to have been left out of `verse` images that use **tinytex**.  (See the FAQ, end of Q#6: https://yihui.name/tinytex/faq/).  I think it's installed in the base `r-ver` but is then removed after building R.

**Comment by cboettig** [comment]
ah, good catch, missed that being external to TinyTex.  Want to send a PR?
