### ISSUE TITLE
Consider cleaner RStudio defaults for handling history

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned#79]
Current default creates `.Rhistory` and always creates and loads `.RData` on exit / startup.  For sake of reproducibility, tidy git repos, etc, I think we should turn these settings off in the 'global' config.

Looks like we can achieve this by editing `~/.rstudio/monitored/user-settings` as follows:

- [ ] `alwaysSaveHistory="1"` -> `alwaysSaveHistory="0"`
- [ ] `loadRData="1"` -> `loadRData="0"`
- [ ] `saveAction="-1"` -> `saveAction="0"`

(not sure if this file is created before startup, may have to do at runtime?)

Of course users can already set the global and project defaults from RStudio once they log in.

**Comment by timtrice** [comment]
I do not believe this file is created until you modify the settings though I could be wrong. My workaround was to wget the settings from a gist and save them to the directory you clarified above, which I had to create in my Dockerfile.

Happy to look into it further and find a cleaner way.

**Comment by timtrice** [comment]
Apologies for all the commit amends. I was trying to clean the formatting and forgot it would show up here.

**Comment by cboettig** [comment]
Closed by #80
