### ISSUE TITLE
Systematic build failures?

### ISSUE THREAD

**Issue by eddelbuettel** [rocker-org/rocker-versioned#8]
See https://hub.docker.com/r/rocker/r-versioned/builds/

Maybe we want to 'park' or comment-out a few of these?

**Comment by cboettig** [comment]
yups, should just drop the waterfall triggers so they don't re-build when r-base builds.    

In other news, I wonder if there's a good strategy to avoid repeating code that is shared across Dockerfiles that use the same build-R-from-source recipe, e.g. pulling in that code from a script.  I guess currently you have to maintain that separately for r-devel, drd, and san / ubsan-clang flavors?

**Comment by eddelbuettel** [comment]
Sounds good stopping the waterfall.

As for 'templating' the Dockerfiles: maybe.  But so far I dealt with maybe four at the most so I have not been too inspired to think about tooling...
