### ISSUE TITLE
Should rocker-versioned stack provide Docker's debian build-deps stack?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/rocker-versioned#81]
e.g. see https://github.com/docker-library/buildpack-deps/blob/d7da72aaf3bb93fecf5fcb7c6ff154cb0c55d1d1/stretch/Dockerfile

most of these get picked up at one level or another through the stack anyway, but could be added lower down (say at `r-ver` or RStudio.  Looks like including these would have a relatively small increase to the image size (adding ~ 50 MB when compressed).

**Comment by eddelbuettel** [comment]
¯\_(ツ)_/¯

I learned about these approximately seven minutes ago per your comment :)  If you think they, use them.  As a Debian'er I tend to think we have a handle on our dependencies but Stockholm Syndrome, Tunnel Vision, and all that...
