### ISSUE TITLE
RStudio initialization error: Error occurred during transmission

### ISSUE THREAD

**Issue by zkamvar** [rocker-org/rocker-versioned#82]
I am getting an error attempting to run the rstudio container:

```
$ docker run -d -p 8787:8787 rocker/rstudio:latest
c5fea7ee86078fe05a1460c68fd66a7907f2006edf31e30ed6866e86c1f04d53
```

When I open `localhost:8787` in my browser (I've tried both Firefox and Safari) and enter in the credentials, I get the following error dialog:

![Dialog box that is titled "RStudio initialization error" and shows the message "Error occurred during transmission" with an "OK" button](https://user-images.githubusercontent.com/3639446/38511202-054bb73a-3bed-11e8-830f-cc87009716d0.png)

I don't know if it helps, but I get the following output from curl:

```
$ docker run -d -p 8787:8787 rocker/rstudio:latest; sleep 10
fbd57ff10c7be8b553fad381199c49defd520fc19af5d0f96b4eb714b562bcf3
$ curl --retry 10 --retry-delay 5 -v http://localhost:8787
* Rebuilt URL to: http://localhost:8787/
*   Trying ::1...
* Connected to localhost (::1) port 8787 (#0)
> GET / HTTP/1.1
> Host: localhost:8787
> User-Agent: curl/7.49.0
> Accept: */*
>
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html
< Content-Length: 60
< Location: http://localhost:8787/unsupported_browser.htm
< Date: Mon, 09 Apr 2018 16:59:58 GMT
< Connection: close
< Server: RStudio
<
* Closing connection 0
```

**Comment by timtrice** [comment]
Possibly related to #79, PR #80

**Comment by timtrice** [comment]
I can't look into this at the moment but happy to try tonight

**Comment by timtrice** [comment]
I'm unable to replicate this issue given the example provided. I'm able to log into RStudio 3.4.4 without issue.

@zkamvar , this issue may be unrelated. However, the only time I have seen this error message is with trying to import the user-settings file for RStudio. These are preset customizations (see [my gist](https://gist.github.com/timtrice/94a679b51388faf99ef7918c7bdaff8d), for example). If the file isn't accessible by the user then this error pops up.

Log into the container and go to /home/rstudio/. If you see the .rstudio (note the preceeding dot), then you should see the file monitored/user-settings/user-settings

If so, let me know what the permissions and owner of the file are, please.

**Comment by zkamvar** [comment]
Hello,

Embarrassingly, I am also unable to reproduce this 😞. I'm going to chalk this up to Docker being super wonky on MacOS in their most recent release. Thanks for checking!

**Comment by timtrice** [comment]
No worries; now you know what to look for next time you get it.

**Comment by gadenbuie** [comment]
I just ran into this problem myself, and after *far too much* trial, error, and Googling I discovered [this small comment](https://forums.docker.com/t/no-space-left-on-device-error/10894/2) on the Docker forums:

> It's possibly because the `Docker.qcow2` is full ... The disk is a 64GB Sparse Image that will expand on demand… We currently aren’t able to reclaim unused space but we’ll hopefully have a fix in a future beta. You can delete this file providing you aren’t worried about loosing any containers/images, and restart Docker. This should get you back on track.

Upon investigation this file was near the 64GB limit on my MacOS machine, and after deleting it, restarting Docker, and re-pulling/building images everything is working again. 

The full path to the file on my system was

```
~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

**Comment by bruth** [comment]
> However, the only time I have seen this error message is with trying to import the user-settings file for RStudio. These are preset customizations (see my gist, for example). If the file isn't accessible by the user then this error pops up.

I know this is an old issue, but just wanted to leave a note after observing this problem myself. It was a permission issue with the user-settings which caused the initialization error.

**Comment by lwaldron** [comment]
> I just ran into this problem myself, and after _far too much_ trial, error, and Googling I discovered [this small comment](https://forums.docker.com/t/no-space-left-on-device-error/10894/2) on the Docker forums:
> 
> > It's possibly because the `Docker.qcow2` is full ... The disk is a 64GB Sparse Image that will expand on demand… We currently aren’t able to reclaim unused space but we’ll hopefully have a fix in a future beta. You can delete this file providing you aren’t worried about loosing any containers/images, and restart Docker. This should get you back on track.
> 
> Upon investigation this file was near the 64GB limit on my MacOS machine, and after deleting it, restarting Docker, and re-pulling/building images everything is working again.
> 
> The full path to the file on my system was
> 
> ```
> ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
> ```

Something similar fixed the problem for me too on OSX, but it was Whale icon -> Preferences -> Resources -> Advanced -> Disk image size. It showed the entire disk in use, and just enlarging the disk and selecting "Apply & Restart" worked.
