### ISSUE TITLE
RStudio terminal does not work

### ISSUE THREAD

**Issue by aabor** [rocker-org/rocker-versioned#83]
I start RStudio in docker container by command
   `` docker run -d  -p 8787:8787 rocker/tidyverse:latest``
RStudio opens fine in the browser Firefox Developer Edition 60.0b12 (64-bit), but terminal does not seems to work. Terminal window is opening, but text enter is not possible. I tried to stop all extensions and add-ons with no effect.
I want to execute some git commands in the shell. It is not possible now. 
I use Docker Version 18.03.0-ce-win59 (16762) Channel: stable d70d80d under windows 10 Pro.

**Comment by amoeba** [comment]
Hey @aabor does it work for you on any other browsers? I just tested here on Firefox (stable), Chrome (stable) and the Terminal tab works fine. I tested on Developer Edition and it doesn't work, as you describe. This sounds like a Firefox Developer Edition issue rather than a rocker issue. What do you think?

**Comment by amoeba** [comment]
Glad to hear it, @aabor! If you have no other issues, the maintainers of this project might appreciate if you close this issue when you get a chance.

**Comment by kforner** [comment]
Have you tried to uncheck "connect with WebSockets" in Tool -> Options -> Terminal ?
works for me in firefox.

**Comment by aabor** [comment]
Hi @kforner! I`ve just unchecked the option "connect with WebSockets" in Tool -> Options -> Terminal and the RStudio terminal opens successfully in docker container in Firefox Developer Edition.

**Comment by erniee** [comment]
Does anyone know if there is a way to start the container with this setting already set to false?

**Comment by FernandezMathieu** [comment]
> Does anyone know if there is a way to start the container with this setting already set to false?

Hey, did you found a response to this ?

**Comment by cboettig** [comment]
FWIW I am running the current Firefox (v73.0) and have no issues with the RStudio terminal now.

**Comment by FernandezMathieu** [comment]
Well, i try both (Chrome & Firefox) and i still have the terminal not showing anything..
