### ISSUE TITLE
windows/screen is greyed out when run shiny app or rstudio addin gadget

### ISSUE THREAD

**Issue by shizidushu** [rocker-org/rocker-versioned#85]
I opened this issue 2 days ago in [shiny github repo](https://github.com/rstudio/shiny/issues/2053). @wch said "This sounds like an issue with your Docker setup". 

I build [my docker image](https://github.com/shizidushu/rstudio-plus-shiny-server-dockerfile) based on rocker/verse.

In order to make this issue more reproducible. I just test it with rocker/verse in my remote server.

```bash
docker run --rm -p 8787:8787 rocker/verse
```

Then open the rstudio server in the remote server. 

Click the upper left + sign, then "Shiny Web App", assign a name, click "Create", at last click "Run App".

The browser pops up a window. The window shown greyed out

**Comment by eitsupi** [comment]
Close the issue due to lack of information. If a similar problem occurs again, please open a new issue at https://github.com/rocker-org/rocker-versioned2.
