### ISSUE TITLE
Shiny should be included by default

### ISSUE THREAD

**Issue by joerg** [rocker-org/rocker-versioned#86]
Hi,
I have to work in an airgapped environment, meaning that my servers have no active internet connection. Thus running with "-e ADD=shiny" is not possible since that would require an active internet connection.
Do you think it would be possible to provide shiny preinstalled in the image instead of installing it on the fly in the container? That would also make everything more reproducible.
In the end, the only change required would be to run the add_shiny.sh in the Dockerfile ...
What do you think? Any suggestions on this? Do you want a pull request for this?

**Comment by eddelbuettel** [comment]
Does this help?  

https://github.com/rocker-org/shiny

**Comment by joerg** [comment]
I know this Image, yes, but the problem is, that it is not versioned. For a production deployment this would be quite suboptimal.
I understand that adding shiny by default would be problematic in some ways. Maybe versioning shiny would be possilbe? I am not too familiar with R and its environment, but Docker is my topic so I can help here if you want...

**Comment by eddelbuettel** [comment]
Methinks the easiest would just be for you to take our versioned images, run `ADD=shiny` for a local container and deploy that locally.

**Comment by joerg** [comment]
Well, as I already explained that is not possible due to the lack of an active internet connection.

**Comment by eddelbuettel** [comment]
Let me be more explicit:
- use computer _with_ a connection
- pull our image 
- modify it by adding shint
- transfer the modified image

You obviously can get our unmodified containers to the air-gapped machine, you should be able to get a modified one there too.   We do this as volunteers, and we cannot accomodate every change request that comes in.  Sorry.

**Comment by joerg** [comment]
If it would be that easy I'd already done it some time ago. All we have is a proxy cache that lets us pull docker images. Nothing else is possible and will not be permitted by our local security.
But I see that there is an unwillingness to include shiny by default and I have to accept that. Do you think version tagging the shiny image would be an option?

**Comment by joerg** [comment]
Ok, I've come to the conclusion that versioning shiny would be a lot better than including it here by default. Sorry for bugging you, but I will open a new ticket for shiny...
