### ISSUE TITLE
r-ver/r-base packrat compatibility regarding r-recommends

### ISSUE THREAD

**Issue by dbast** [rocker-org/rocker-versioned#92]
Dear rocker team,

while testing r-ver/r-base based images together with packrat, I noticed that the later have the r-recommended packages installed, whereas the former images are compiled with the option "--without-recommended-packages".

Packrat libraries, created on top of a R installation with the recommended packages installed, contain every private package but the recommended packages are excluded and as such not part of the packrat.lock file. (Packrat will include the recommended packages if those are not a given by the R installation.)

This is also stated in the packrat documentation (p5 in [packrat.pdf](https://cran.r-project.org/web/packages/packrat/packrat.pdf)): Calls to require and library will load packages from the private library (except for ’base’ or ’recommended’ R packages, which are found in the system library).

That means that many packrat libraries, that where created with r-recommends installed, can be restored on top of the r-base based images, but not on top of the r-ver images. Restoring on top of the later will result in unresolved dependencies and would require adding those also to the packrat library.

This can be resolved by changing the r-ver images to "--with-recommended-packages" and would increase the compatibility for packrat users, working on different distributions / mixing r-ver/r-base based workflows etc.

This should be still in accordance to the r-ver philosophy, where everything is versioned, as the r-recommended packages all have a specific version for every R version, see also:
- https://cran.r-project.org/src/contrib/3.5.1/Recommended/
- https://github.com/wch/r-source/blob/trunk/tools/rsync-recommended

If this is reasonable, I can provide a PR changing this in all r-ver images.

What do you think?

Thanks

Daniel

**Comment by cboettig** [comment]
Hi Daniel,

Thanks for this, I hadn't realized that particular failure mode for packrat -- it seems a bit surprising to me that packrat would not treat 'recommended' packages the same way as other packages (i.e. tracking their explicit versions in the `.lock` file.  Sure they are pretty stable packages but seems like it would have been better to treat them as such.  So packrat won't simply install those into it's 'local' library if it needs them? (i.e. if they are dependencies of things in the lock file?) 

So you are proposing we just default to the corresponding MRAN snapshot for the recommended packages, and ship recommended packages in `r-ver`?  They are pretty small, so this doesn't seem un-reasonable, but doesn't seem ideal to me either. (Maybe I'm just not thinking about this correctly).  Maybe we can get @kevinushey to comment on why packrat treats r-recommended packages this way and what the best choice might be here?

**Comment by eddelbuettel** [comment]
I think it is partially R influenced: they both permit splitting off the recommended packages (as we do here) but also consider it very unlikely to not have them.  For Debian I have them split off (and regrouped in the empty meta package r-recommended) but it is generally seen as "very unlikely" that the packages would not ship with R.  (Also, at build time from sources you can run a shell script to rsync them in.)

Can you not just build them at container creation time?

**Comment by dbast** [comment]
Well, there are three solutions to this:
1. Delegate it to the packrat user: By manually adding all required recommended packages to the packrat library, the library can be restored on any top of any type of r-base/r-apt/r-ver based R Docker image:
  * Advantages:
    * 100% versioning
  * Disadvantages:
    * manual process for the user, as packrat uses system provided recommended packages if available and it is intransparent which of those are used.
2. Add recommended packages during container creation via R installer (configure option).
  * Advantages:
    * Mechanism already provided by the R installer -> nothing to be maintained
    * Also versioning somehow guaranteed via special CRAN folder per R version: https://cran.r-project.org/src/contrib/${R-Version}/Recommended/
  * Disadvantages:
    * Versioning maybe not 100%?
3. Add recommended packages during container creation via install.packages from versioned MRAN mirror:
  * Advantages:
    * Almost 100% versioning
  * Disadvantages:
    * Would be a manually combined list of packages, that may change from R version to R version. The actual list can be found here https://github.com/wch/r-source/blob/trunk/share/make/vars.mk#L12 ... could be extracted via grep/sed etc. and installed.
    * Versioning maybe not 100% as the MRAN snapshot version could be different to the one in the special folder https://cran.r-project.org/src/contrib/${R-Version}/Recommended/

As option 2 is provided by the R installer itself, it sounds most natural to me. Created a pull request with that solution. Option 3 should also be doable if prefered. 

Thanks

Daniel

**Comment by kevinushey** [comment]
Because recommended R packages are available by default in the binaries released by CRAN on Windows + macOS, and because installing R from package repositories typically provides one with recommended R packages, we took the world-view that R installations would provide recommended R packages by default and so could avoid some potentially annoying re-installations of packages normally available with R. (This decision was made before Packrat had a global package cache that could be reused for different projects).

For what it's worth, in Packrat this can be configured with a project-specific option, e.g. from `?"packrat-options"`:

        • 'snapshot.recommended.packages': Should 'recommended'
          packages discovered in the system library be snapshotted? See
          the 'Priority' field of 'available.packages()' for more
          information - 'recommended' packages are those normally
          bundled with CRAN releases of R on OS X and Windows, but new
          releases are also available on CRAN.  (logical;
          defaults to 'FALSE')

**Comment by cboettig** [comment]
Thanks @kevinushey !  So based on this, I'm curious what you would recommend here?  

Theoretically, I think it would be preferable for `packrat` to default to `snapshot.recommended.packages = TRUE`, since that seems the more robust and users could opt-out at their peril?  Given that I believe recommended packages like `lattice` could be updated in between R releases (since recommended packages are still on CRAN, not like base R packages), I think it's preferable they be treated like other CRAN packages and get explicit versioning...

So, I'm still undecided if we should just go the route of #93 so at least packrat projects can run out of the box, or if we can somehow set that as the default behavior for packrat to run when importing a package in the rstudio container.  (e.g. guessing that option needs to be set on the R installation which is creating the packrat archive, not the instance that is opening it?)  Would it be possible for us to set an option on the container such that packrat would simply install all recommended packages automatically (matching the version to the R release) when opening a packrat project that had not tracked these explicitly?

**Comment by kevinushey** [comment]
Note that we do snapshot recommended packages, but only when they're discovered in the user library (ie the user has already made it clear that they intend to depend on a version of the package not available 'by default').

IMHO recommended packages should just be installed by default.

**Comment by cboettig** [comment]
Thanks @kevinushey , that makes sense.  Just for clarity here, what do you mean by "user library" and "default"? 

 i.e. rocker images install all packages to `/usr/local/lib/R/site-library` (the first entry in `.libPaths()`, whether they are installed by root or interactively later by the user (who is a member of the `staff` group by default in rocker images).  Is that considered the "user library" to packrat then?

**Comment by kevinushey** [comment]
By user library I mean the library normally specified by `R_LIBS_USER`; e.g. from `?Startup`:

     By default 'R_LIBS' is unset, and 'R_LIBS_USER' is set to
     directory 'R/R.version$platform-library/x.y' of the home directory
     (or 'Library/R/x.y/library' for CRAN macOS builds), for R x.y.z.

That said Packrat might just consider whatever is seen 'first' in the library path as the user library so your site library in this case might be considered the user library -- would need to test Packrat to be sure.

**Comment by eddelbuettel** [comment]
... which is something the Debian builds turn off -- note the leading `#` here (and comments in the file):

```
edd@rob:~$ grep R_LIBS /etc/R/Renviron.site
# R_LIBS=~/R/library
# R_LIBS=C:/R/library
#R_LIBS_USER=${R_LIBS_USER-'~/R/@R_PLATFORM@-library/@MAJ_MIN_VERSION@'}
#R_LIBS_USER=${R_LIBS_USER-'~/R/@R_PLATFORM@/@MAJ_MIN_VERSION@'}
#R_LIBS_USER=${'~/R/@R_PLATFORM@/@MAJ_MIN_VERSION@'}
#R_LIBS=${'~/R/'}
edd@rob:~$ Rscript -e 'print(.libPaths())'
[1] "/usr/local/lib/R/site-library" "/usr/lib/R/site-library"       "/usr/lib/R/library"
edd@rob:~$
```

So r-ver could turn it back on.   Or, as Kevin suggested, maybe just install the then-current r-recommended packages?

**Comment by kevinushey** [comment]
I do get a user library with by (from Debian repository) R installation though:

```
$ Rscript -e 'print(.libPaths())'
[1] "/home/kevin/R/x86_64-pc-linux-gnu-library/3.4"
[2] "/usr/local/lib/R/site-library"                
[3] "/usr/lib/R/site-library"                      
[4] "/usr/lib/R/library"
```

Looks like it's still set in `/etc/r/Renviron`:

```
kevin@ubuntu:~
$ grep R_LIBS_USER /etc/R/Renviron
R_LIBS_USER=${R_LIBS_USER-'~/R/x86_64-pc-linux-gnu-library/3.4'}
#R_LIBS_USER=${R_LIBS_USER-'~/Library/R/3.4/library'}
```

Although that library path only gets used if that directory already exists. I _think_ RStudio automatically creates the directory for you on startup (just so you always get a writable user library) but that probably doesn't happen by default in R.

**Comment by cboettig** [comment]
Right, but on rocker debian, it's just:

```
> .libPaths()
[1] "/usr/local/lib/R/site-library" "/usr/local/lib/R/library"
```

and 

```
 Sys.getenv("R_LIBS")
[1] "/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library"
```

**Comment by cboettig** [comment]
Done in #92
