### ISSUE TITLE
rocker/tidyverse containers close

### ISSUE THREAD

**Issue by mbjoseph** [rocker-org/rocker-versioned#98]
I'm noticing that the latest rocker/tidyverse containers exit shortly after being run. When I start a container via:

```
docker run -d -p 8787:8787 rocker/tidyverse
```

A container runs for just a few seconds (according to `docker ps`), then is exited immediately. I would expect that this container does not exit, but rather continues to run so I can connect to RStudio server. 

I'm using Docker version 17.12.1-ce, build 7390fc6 in Ubuntu Bionic Beaver, but I've also recreated the same behavior in Docker version 18.06.1-ce, build e68fc7a215d7133c34aa18e3b72b4a21fd0c6136 on Amazon Linux. 

Any hints as to how to prevent this from happening?

**Comment by cboettig** [comment]
Sorry, we made password (other than rstudio) required to enforce better security behavior.  (You'll see an error to this effect in `docker logs`

**Comment by cboettig** [comment]
e.g. you now need to do something like:

    docker run -e PASSWORD=yourpassword --rm -p 8787:8787 rocker/rstudio


(https://www.rocker-project.org)

**Comment by mbjoseph** [comment]
Awesome! This is a good change. Thanks for the explanation @cboettig
